SHOWS_MAP = {
    '24 legacy': '24 - Legacy',
    'abstract': 'Abstract - The Art Of Design',
    'abstract the art of design': 'Abstract - The Art Of Design',
    'ally mcbeal': 'Ally McBeal',
    'american dad!': 'American Dad',
    'the americans': 'The Americans (2013)',
    'archer': 'Archer (2009)',
    'avatar': 'Avatar - The Last Airbender',
    'avatar the last airbender': 'Avatar - The Last Airbender',
    'batman': 'Batman - The Animated Series',
    'batman the animated series': 'Batman - The Animated Series',
    'battlestar galactica': 'Battlestar Galactica (2003)',
    'beverly hills': 'Beverly Hills, 90210',
    'beverly hills 90210': 'Beverly Hills, 90210',
    'the blacklist redemption': 'The Blacklist - Redemption',
    'the bridge': 'The Bridge (2011)',
    'brooklyn nine nine': 'Brooklyn Nine-Nine',
    'buffy': 'Buffy - The Vampire Slayer',
    'buffy the vampire slayer': 'Buffy - The Vampire Slayer',
    'castle': 'Castle (2009)',
    'chappelles show': 'Chappelle\'s Show',
    'chefs table': 'Chef\'s Table',
    'chefs table france': 'Chef\'s Table - France',
    'cosmos': 'Cosmos - A Spacetime Odyssey',
    'cosmos a spacetime odyssey': 'Cosmos - A Spacetime Odyssey',
    'dcs legends of tomorrow': 'DC\'s Legends Of Tomorrow',
    'legends of tomorrow': 'DC\'s Legends Of Tomorrow',
    'dirk gentlys holistic detective agency': 'Dirk Gently\'s Holistic Detective Agency',
    'doctor who': 'Doctor Who (2005)',
    'dragon ball gt': 'Dragon Ball GT',
    'empire': 'Empire (2015)',
    'the flash': 'The Flash (2014)',
    'flashforward': 'FlashForward',
    'the fosters': 'The Fosters (2013)',
    'the fresh prince of bel air': 'The Fresh Prince Of Bel-Air',
    'fullmetal alchemist brotherhood': 'Fullmetal Alchemist - Brotherhood',
    'gilmore girls a year in the life': 'Gilmore Girls - A Year In The Life',
    'ghost in the shell arise alternative architecture': 'Ghost In The Shell - Arise - Alternative Architecture',
    'ghost in the shell stand alone complex': 'Ghost In The Shell - Stand Alone Complex',
    'the grand tour': 'The Grand Tour (2016)',
    'greys anatomy': 'Grey\'s Anatomy',
    'haikyuu!': 'Haikyuu',
    'haikyuu!!': 'Haikyuu',
    'house of cards': 'House Of Cards (US)',
    'hunter x hunter': 'Hunter X Hunter (2011)',
    'the it crowd': 'The IT Crowd',
    'its always sunny in philadelphia': 'It\'s Always Sunny In Philadelphia',
    'james clavells shogun': 'James Clavell\'s Shogun',
    'shogun': 'James Clavell\'s Shogun',
    'jericho': 'Jericho (2006)',
    'the jinx': 'The Jinx - The Life And Deaths Of Robert Durst',
    'the jinx the life and deaths of robert durst': 'The Jinx - The Life And Deaths Of Robert Durst',
    'the killing': 'The Killing (2011)',
    'life': 'Life (2009)',
    'lois & clark': 'Lois And Clark - The New Adventures Of Superman',
    'lois & clark the new adventures of superman': 'Lois And Clark - The New Adventures Of Superman',
    'lois and clark': 'Lois And Clark - The New Adventures Of Superman',
    'lois and clark the new adventures of superman': 'Lois And Clark - The New Adventures Of Superman',
    'louie': 'Louie (2010)',
    'the magicians': 'The Magicians (2015)',
    'marco polo': 'Marco Polo (2014)',
    'married. with children': 'Married With Children',
    'married... with children': 'Married With Children',
    'agent carter': 'Marvel\'s Agent Carter',
    'marvels agent carter': 'Marvel\'s Agent Carter',
    'agents of s.h.i.e.l.d.': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'marvels agents of shield': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'marvels agents of s.h.i.e.l.d': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'marvels agents of s.h.i.e.l.d.': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'daredevil': 'Marvel\'s Daredevil',
    'marvels daredevil': 'Marvel\'s Daredevil',
    'iron fist': 'Marvel\'s Iron Fist',
    'marvels iron fist': 'Marvel\'s Iron Fist',
    'jessica jones': 'Marvel\'s Jessica Jones',
    'marvels jessica jones': 'Marvel\'s Jessica Jones',
    'luke cage': 'Marvel\'s Luke Cage',
    'marvels luke cage': 'Marvel\'s Luke Cage',
    'medici': 'Medici - Masters Of Florence',
    'medici masters of florence': 'Medici - Masters Of Florence',
    'mob psycho': 'Mob Psycho 100',
    'mortal kombat legacy': 'Mortal Kombat - Legacy',
    'mr robot': 'Mr. Robot',
    'mythbusters': 'MythBusters',
    'niptuck': 'NipTuck',
    'nip tuck': 'NipTuck',
    'the oa': 'The OA',
    'the office': 'The Office (US)',
    'the venture bros': 'The Venture Bros.',
    'once upon a time': 'Once Upon A Time (2011)',
    'one punch man': 'One-Punch Man',
    'parasyte': 'Parasyte - The Maxim',
    'parasyte the maxim': 'Parasyte - The Maxim',
    'ping pong': 'Ping Pong - The Animation',
    'ping pong the animation': 'Ping Pong - The Animation',
    'planet earth ii': 'Planet Earth II',
    'r o d': 'R.O.D - Read Or Die',
    'r.o.d': 'R.O.D - Read Or Die',
    'read or die': 'R.O.D - Read Or Die',
    'r.o.d read or die': 'R.O.D - Read Or Die',
    'roots': 'Roots (2016)',
    'scandal': 'Scandal (2012)',
    'second chance': 'Second Chance (2016)',
    'shameless': 'Shameless (US)',
    'six': 'SIX',
    'spiderman': 'Spider-Man (1994)',
    'spider man': 'Spider-Man (1994)',
    'spider-man': 'Spider-Man (1994)',
    'ss': 'SS-GB',
    'ss gb': 'SS-GB',
    'ss-gb': 'SS-GB',
    'stargate atlantis': 'Stargate - Atlantis',
    'stargate': 'Stargate - SG-1',
    'stargate sg-1': 'Stargate - SG-1',
    'stargate sg 1': 'Stargate - SG-1',
    'steinsgate': 'Steins;Gate',
    'steins gate': 'Steins;Gate',
    'taboo': 'Taboo (2017)',
    'that 70s show': 'That 70\'s Show',
    'this is': 'This Is Us',
    'vice': 'VICE',
    'walker': 'Walker, Texas Ranger',
    'walker texas ranger': 'Walker, Texas Ranger',
    'welcome to': 'Welcome To Sweden (2014)',
    'welcome to sweden': 'Welcome To Sweden (2014)',
    'wilfred': 'Wilfred (US)',
    'wrecked': 'Wrecked (2016)',
    'the x files': 'The X-Files',
    'x men': 'X-Men - The Animated Series',
    'x men the animated series': 'X-Men - The Animated Series'
}
