SHOWS_MAP = {
    '24 legacy': '24 - Legacy',
    '3%': '3 Percent',
    '7seeds': '7Seeds',
    '911': '9-1-1',
    '9 1 1': '9-1-1',
    '911 lone star': '9-1-1 - Lone Star',
    '9-1-1 lone star': '9-1-1 - Lone Star',
    '9 1 1 lone star': '9-1-1 - Lone Star',
    'a team': 'The A-Team',
    'a-team': 'The A-Team',
    'the a team': 'The A-Team',
    'the a-team': 'The A-Team',
    'the abc murders': 'The ABC Murders',
    'abstract': 'Abstract - The Art Of Design',
    'abstract the art of design': 'Abstract - The Art Of Design',
    'adventure time with finn and jake': 'Adventure Time',
    'a i the end of humanity': 'A.I. - The End Of Humanity',
    'a.i the end of humanity': 'A.I. - The End Of Humanity',
    'a.i. the end of humanity': 'A.I. - The End Of Humanity',
    'a i - the end of humanity': 'A.I. - The End Of Humanity',
    'a.i - the end of humanity': 'A.I. - The End Of Humanity',
    'a.i. - the end of humanity': 'A.I. - The End Of Humanity',
    'akame ga kill': 'Akame Ga Kill!',
    'al haspektrum': 'On The Spectrum',
    'aldnoah.zero': 'Aldnoah.Zero',
    'aldnoah zero': 'Aldnoah.Zero',
    'alex inc': 'Alex, Inc.',
    'alex, inc': 'Alex, Inc.',
    'alex inc.': 'Alex, Inc.',
    'all american': 'All American (2018)',
    'all or nothing manchester city': 'All Or Nothing - Manchester City',
    'all or nothing new zealand all blacks': 'All Or Nothing - New Zealand All Blacks',
    'all or nothing tottenham hotspur': 'All Or Nothing - Tottenham Hotspur',
    'ally mcbeal': 'Ally McBeal',
    'american dad': 'American Dad!',
    'the americans': 'The Americans (2013)',
    'amazing stories': 'Amazing Stories (2020)',
    'angel beats': 'Angel Beats!',
    'animal kingdom': 'Animal Kingdom (2016)',
    'animals': 'Animals.',
    'animaniacs': 'Animaniacs (2020)',
    'ano hi mita hana': 'Anohana - The Flower We Saw That Day',
    'another life': 'Another Life (2019)',
    'ap bio': 'A.P. BIO',
    'a p bio': 'A.P. BIO',
    'a.p bio': 'A.P. BIO',
    'a.p. bio': 'A.P. BIO',
    'aquarius': 'Aquarius (2015)',
    'aquarius us': 'Aquarius (2015)',
    'archer': 'Archer (2009)',
    'ash vs evil dead': 'Ash Vs. Evil Dead',
    'avatar': 'Avatar - The Last Airbender',
    'avatar the last airbender': 'Avatar - The Last Airbender',
    'awkward': 'Awkward.',
    'baki': 'Baki (2018)',
    'barbarians': 'Barbarians (2020)',
    'batman': 'Batman - The Animated Series',
    'batman the animated series': 'Batman - The Animated Series',
    'battlebots': 'BattleBots (2015)',
    'battlestar galactica': 'Battlestar Galactica (2003)',
    'beauty and the beast': 'Beauty And The Beast (2012)',
    'beavis and butthead': 'Beavis And Butt-Head',
    'beavis and butt-head': 'Beavis And Butt-Head',
    'bein arizona lnes ziona': 'Between Arizona And Nes Ziona',
    'being human': 'Being Human (US)',
    'betipul': 'In Therapy',
    'beverly hills': 'Beverly Hills, 90210',
    'beverly hills 90210': 'Beverly Hills, 90210',
    'bh90210': 'BH90210',
    'bh 90210': 'BH90210',
    'big sky': 'Big Sky (2020)',
    'blackaf': 'BlackAF',
    'black af': 'BlackAF',
    'blackish': 'Black-Ish',
    'black-ish': 'Black-Ish',
    'the blacklist redemption': 'The Blacklist - Redemption',
    'blood and treasure': 'Blood & Treasure',
    'blue planet ii': 'Blue Planet II',
    'bobs burgers': 'Bob\'s Burgers',
    'bob\'s burgers': 'Bob\'s Burgers',
    'bodyguard': 'Bodyguard (2018)',
    'boku dake ga inai machi': 'ERASED',
    'boku no hero academia': 'My Hero Academia',
    'boruto': 'Boruto – Naruto Next Generations',
    'boruto naruto next generations': 'Boruto – Naruto Next Generations',
    'braindead': 'BrainDead',
    'brave new world': 'Brave New World (2020)',
    'breakfast lunch and dinner': 'Breakfast, Lunch & Dinner',
    'breakfast lunch & dinner': 'Breakfast, Lunch & Dinner',
    'breakfast, lunch and dinner': 'Breakfast, Lunch & Dinner',
    'the bridge': 'The Bridge (2011)',
    'brooklyn nine nine': 'Brooklyn Nine-Nine',
    'btooom': 'BTOOOM!',
    'btooom!': 'BTOOOM!',
    'buffy': 'Buffy - The Vampire Slayer',
    'buffy the vampire slayer': 'Buffy - The Vampire Slayer',
    'bull': 'Bull (2016)',
    'call my agent': 'Call My Agent!',
    'carols second act': 'Carol\'s Second Act',
    'castle': 'Castle (2009)',
    'catastrophe': 'Catastrophe (2015)',
    'catch 22': 'Catch-22',
    'chambers': 'Chambers (2019)',
    'chappelles show': 'Chappelle\'s Show',
    'chappelle\'s show': 'Chappelle\'s Show',
    'charmed': 'Charmed (2018)',
    'cheer': 'Cheer (2020)',
    'chefs table': 'Chef\'s Table',
    'chef\'s table': 'Chef\'s Table',
    'chefs table france': 'Chef\'s Table - France',
    'chef\'s table france': 'Chef\'s Table - France',
    'chicago pd': 'Chicago P.D.',
    'chicago p d': 'Chicago P.D.',
    'chicago p.d': 'Chicago P.D.',
    'chicago p.d.': 'Chicago P.D.',
    'children of dune': 'Frank Herbert\'s Children Of Dune',
    'the chilling adventures of sabrina': 'Chilling Adventures Of Sabrina',
    'cobra': 'COBRA (2020)',
    'connecting': 'Connecting...',
    'crashing': 'Crashing (2017)',
    'crazy ex girlfriend': 'Crazy Ex-Girlfriend',
    'crazy ex-girlfriend': 'Crazy Ex-Girlfriend',
    'frank herberts children of dune': 'Frank Herbert\'s Children Of Dune',
    'frank herbert\'s children of dune': 'Frank Herbert\'s Children Of Dune',
    'dune': 'Frank Herbert\'s Dune',
    'frank herberts dune': 'Frank Herbert\'s Dune',
    'frank herbert\'s dune': 'Frank Herbert\'s Dune',
    'conversations with a killer the ted bundy tapes': 'Conversations With A Killer - The Ted Bundy Tapes',
    'cosmos a spacetime odyssey': 'Cosmos (2014)',
    'criminal minds beyond borders': 'Criminal Minds - Beyond Borders',
    'criminal uk': 'Criminal - United Kingdom',
    'criminal united kingdom': 'Criminal - United Kingdom',
    'cursed': 'Cursed (2020)',
    'da vincis demons': 'Da Vinci\'s Demons',
    'da vinci\'s demons': 'Da Vinci\'s Demons',
    'dark': 'DARK',
    'the dark crystal age of resistance': 'The Dark Crystal - Age Of Resistance',
    'darling in the franxx': 'Darling In The FranXX',
    'danmachi': 'Is It Wrong To Try To Pick Up Girls In A Dungeon',
    'darwins game': 'Darwin\'s Game',
    'darwin\'s game': 'Darwin\'s Game',
    'dave': 'DAVE',
    'dawsons creek': 'Dawson\'s Creek',
    'dawson\'s creek': 'Dawson\'s Creek',
    'dcs legends of tomorrow': 'DC\'s Legends Of Tomorrow',
    'dc\'s legends of tomorrow': 'DC\'s Legends Of Tomorrow',
    'legends of tomorrow': 'DC\'s Legends Of Tomorrow',
    'dear': 'Dear...',
    'deception': 'Deception (2018)',
    'dexters lab': 'Dexter\'s Lab',
    'dexter\'s lab': 'Dexter\'s Lab',
    'dirk gentlys holistic detective agency': 'Dirk Gently\'s Holistic Detective Agency',
    'dirk gently\'s holistic detective agency': 'Dirk Gently\'s Holistic Detective Agency',
    'disney gallery the mandalorian': 'Disney Gallery - Star Wars - The Mandalorian',
    'disney gallery star wars the mandalorian': 'Disney Gallery - Star Wars - The Mandalorian',
    'divorce': 'Divorce (2016)',
    'divorce us': 'Divorce (2016)',
    'doctor who': 'Doctor Who (2005)',
    'documentary now': 'Documentary Now!',
    'dont fuck with cats': 'Don\'t F**k With Cats - Hunting An Internet Killer',
    'dont f**k with cats': 'Don\'t F**k With Cats - Hunting An Internet Killer',
    'dont fuck with cats hunting an internet killer': 'Don\'t F**k With Cats - Hunting An Internet Killer',
    'dont f**k with cats hunting an internet killer': 'Don\'t F**k With Cats - Hunting An Internet Killer',
    'dont fuck with cats - hunting an internet killer': 'Don\'t F**k With Cats - Hunting An Internet Killer',
    'dont f**k with cats - hunting an internet killer': 'Don\'t F**k With Cats - Hunting An Internet Killer',
    'dont trust the b---- in apartment 23': 'Don\'t Trust The B---- In Apartment 23',
    'dont trust the bitch in apartment 23': 'Don\'t Trust The B---- In Apartment 23',
    'dororo': 'Dororo (2019)',
    'dr stone': 'Dr. Stone',
    'dracula': 'Dracula (2020)',
    'dragon ball gt': 'Dragon Ball GT',
    'dragon ball heroes': 'Super Dragon Ball Heroes',
    'dynasties uk': 'Dynasties (2018)',
    'dynasties': 'Dynasties (2018)',
    'dynasty': 'Dynasty (2017)',
    'empire': 'Empire (2015)',
    'erased': 'Erased (2017)',
    'euphoria': 'Euphoria (US)',
    'everythings gonna be okay': 'Everything\'s Gonna Be Okay',
    'everything sucks': 'Everything Sucks!',
    'evil genius': 'Evil Genius - The True Story Of America\'s Most Diabolical Bank Heist',
    'evil genius the true story of americas most diabolical bank heist':
        'Evil Genius - The True Story Of America\'s Most Diabolical Bank Heist',
    'evil genius the true story of america\'s most diabolical bank heist':
        'Evil Genius - The True Story Of America\'s Most Diabolical Bank Heist',
    'extinct': 'Extinct (2017)',
    'fateapocrypha': 'Fate - Apocrypha',
    'fate apocrypha': 'Fate - Apocrypha',
    'fategrand order': 'Fate - Grand Order',
    'fate grand order': 'Fate - Grand Order',
    'fategrand order absolute demonic front babylonia': 'Fate - Grand Order - Absolute Demonic Front - Babylonia',
    'fate grand order absolute demonic front babylonia': 'Fate - Grand Order - Absolute Demonic Front - Babylonia',
    'fategrand order absolute demonic front - babylonia': 'Fate - Grand Order - Absolute Demonic Front - Babylonia',
    'fate grand order absolute demonic front - babylonia': 'Fate - Grand Order - Absolute Demonic Front - Babylonia',
    'fategrand order - absolute demonic front babylonia': 'Fate - Grand Order - Absolute Demonic Front - Babylonia',
    'fate grand order - absolute demonic front babylonia': 'Fate - Grand Order - Absolute Demonic Front - Babylonia',
    'fategrand order - absolute demonic front - babylonia': 'Fate - Grand Order - Absolute Demonic Front - Babylonia',
    'fate grand order - absolute demonic front - babylonia': 'Fate - Grand Order - Absolute Demonic Front - Babylonia',
    'fatekaleid liner prisma illya': 'Fate - Kaleid Liner Prisma Illya',
    'fate kaleid liner prisma illya': 'Fate - Kaleid Liner Prisma Illya',
    'fatestay night': 'Fate - Stay Night',
    'fate stay night': 'Fate - Stay Night',
    'fatestay night unlimited blade works': 'Fate - Stay Night - Unlimited Blade Works',
    'fate stay night unlimited blade works': 'Fate - Stay Night - Unlimited Blade Works',
    'fatezero': 'Fate - Zero',
    'fate zero': 'Fate - Zero',
    'fbi': 'FBI',
    'fbi most wanted': 'FBI - Most Wanted',
    'fbi - most wanted': 'FBI - Most Wanted',
    'filthy rich': 'Filthy Rich (US)',
    'the flash': 'The Flash (2014)',
    'flashforward': 'FlashForward',
    'flesh and blood': 'Flesh And Blood (2020)',
    'food wars': 'Food Wars! Shokugeki No Soma',
    'food wars shokugeki no soma': 'Food Wars! Shokugeki No Soma',
    'food wars - shokugeki no soma': 'Food Wars! Shokugeki No Soma',
    'shokugeki no soma': 'Food Wars! Shokugeki No Soma',
    'for the people': 'For The People (2018)',
    'foundation': 'Foundation (2020)',
    'frontier': 'Frontier (2016)',
    'forever': 'Forever (2014)',
    'formula 1': 'Formula 1 - Drive To Survive',
    'formula 1 drive to survive': 'Formula 1 - Drive To Survive',
    'drive to survive': 'Formula 1 - Drive To Survive',
    'the fosters': 'The Fosters (2013)',
    'freezing': 'Freezing (2011)',
    'the fresh prince of bel air': 'The Fresh Prince Of Bel-Air',
    'the fugitive': 'The Fugitive (2020)',
    'fullmetal alchemist brotherhood': 'Fullmetal Alchemist - Brotherhood',
    'code geass': 'Code Geass - Lelouch Of The Rebellion',
    'code geass lelouch of the rebellion': 'Code Geass - Lelouch Of The Rebellion',
    'genius': 'Genius (2017)',
    'gilmore girls a year in the life': 'Gilmore Girls - A Year In The Life',
    'gin no saji': 'Silver Spoon',
    'ghost in the shell arise alternative architecture': 'Ghost In The Shell - Arise - Alternative Architecture',
    'ghost in the shell stand alone complex': 'Ghost In The Shell - Stand Alone Complex',
    'ghosts': 'Ghosts (2019)',
    'glitch': 'Glitch (2015)',
    'glow': 'GLOW',
    'goblin slayer': 'GOBLIN SLAYER',
    'godless': 'Godless (2017)',
    'the goldbergs': 'The Goldbergs (2013)',
    'gordon ramsay uncharted': 'Gordon Ramsay - Uncharted',
    'the grand tour': 'The Grand Tour (2016)',
    'greatest events of world war ii in': 'Greatest Events Of WWII In Colour',
    'greatest events of world war ii in colour': 'Greatest Events Of WWII In Colour',
    'greatest events of world war ii in hd colour': 'Greatest Events Of WWII In Colour',
    'greatest events of wwii in colour': 'Greatest Events Of WWII In Colour',
    'greys anatomy': 'Grey\'s Anatomy',
    'grey\'s anatomy': 'Grey\'s Anatomy',
    'grownish': 'Grown-Ish',
    'grown-ish': 'Grown-Ish',
    'haachayot hamutzlachot sheli': 'My Successful Sisters',
    'ha\'achayot hamutzlachot sheli': 'My Successful Sisters',
    'haborer': 'HaBorer',
    'hagure yuusha no estetica': 'Aesthetica Of A Rogue Hero',
    'haikyuu': 'Haikyuu!!',
    'haikyuu!': 'Haikyuu!!',
    'hajime no ippo new challenger': 'Hajime No Ippo - New Challenger',
    'hajime no ippo rising': 'Hajime No Ippo - Rising',
    'the handmaids tale': 'The Handmaid\'s Tale',
    'the handmaid\'s tale': 'The Handmaid\'s Tale',
    'haparlament': 'The Parliament (Haparlament)',
    'happy': 'Happy!',
    'harmonquest': 'HarmonQuest',
    'hataraku saibou': 'Cells At Work!',
    'hatufim': 'Prisoners Of War',
    'hawaii 5-0': 'Hawaii Five-0',
    'hawaii five-o': 'Hawaii Five-0',
    'hercules': 'Hercules - The Legendary Journeys',
    'hercules the legendary journeys': 'Hercules - The Legendary Journeys',
    'here and now': 'Here And Now (2018)',
    'high maintenance': 'High Maintenance (2016)',
    'high school musical the musical the series': 'High School Musical - The Musical - The Series',
    'hillary': 'Hillary (2020)',
    'hitlers circle of evil': 'Hitler\'s Circle Of Evil',
    'hollywood': 'Hollywood (2020)',
    'home movie the princess bride': 'Home Movie - The Princess Bride',
    'house of cards': 'House Of Cards (US)',
    'hubble': 'Hubble - A Look Into The Universe',
    'hubble a look into the universe': 'Hubble - A Look Into The Universe',
    'hunter x hunter': 'Hunter X Hunter (2011)',
    'hunters': 'Hunters (2020)',
    'ill be gone in the dark': 'I\'ll Be Gone In The Dark',
    'i\'ll be gone in the dark': 'I\'ll Be Gone In The Dark',
    'immigration nation': 'Immigration Nation (2020)',
    'in the dark': 'In The Dark (2019)',
    'the inbetween': 'The InBetween',
    'innocent': 'Innocent (2018)',
    'the innocent man': 'The Innocent Man (2018)',
    'intelligence': 'Intelligence (2014)',
    'inside bills brain decoding bill gates': 'Inside Bill\'s Brain - Decoding Bill Gates',
    'inside bill\'s brain decoding bill gates': 'Inside Bill\'s Brain - Decoding Bill Gates',
    'inside bills brain - decoding bill gates': 'Inside Bill\'s Brain - Decoding Bill Gates',
    'inside bill\'s brain - decoding bill gates': 'Inside Bill\'s Brain - Decoding Bill Gates',
    'instinct': 'Instinct (2018)',
    'inuyasha': 'InuYasha',
    'inu yasha': 'InuYasha',
    'the it crowd': 'The IT Crowd',
    'its always sunny in philadelphia': 'It\'s Always Sunny In Philadelphia',
    'it\'s always sunny in philadelphia': 'It\'s Always Sunny In Philadelphia',
    'izombie': 'iZombie',
    'james clavells shogun': 'James Clavell\'s Shogun',
    'james clavell\'s shogun': 'James Clavell\'s Shogun',
    'shogun': 'James Clavell\'s Shogun',
    'jean claude van johnson': 'Jean-Claude Van Johnson',
    'jean-claude van johnson': 'Jean-Claude Van Johnson',
    'jeffrey epstein': 'Jeffrey Epstein - Filthy Rich',
    'jeffrey epstein filthy rich': 'Jeffrey Epstein - Filthy Rich',
    'jericho': 'Jericho (2006)',
    'the jinx': 'The Jinx - The Life And Deaths Of Robert Durst',
    'the jinx the life and deaths of robert durst': 'The Jinx - The Life And Deaths Of Robert Durst',
    'jojos bizarre adventure': 'JoJo\'s Bizarre Adventure (2012)',
    'jojo\'s bizarre adventure': 'JoJo\'s Bizarre Adventure (2012)',
    'jonathan strange & mr norrell': 'Jonathan Strange And Mr. Norrell',
    'jonathan strange & mr. norrell': 'Jonathan Strange And Mr. Norrell',
    'jonathan strange and mr norrell': 'Jonathan Strange And Mr. Norrell',
    'jonathan strange and mr. norrell': 'Jonathan Strange And Mr. Norrell',
    'jurassic world camp cretaceous': 'Jurassic World - Camp Cretaceous',
    'kacha ze': 'Significant Other',
    'kevin (probably) saves the world': 'Kevin (Probably) Saves The World',
    'kevin probably saves the world': 'Kevin (Probably) Saves The World',
    'kevin saves the world': 'Kevin (Probably) Saves The World',
    'kfulim': 'False Flag',
    'the killing': 'The Killing (2011)',
    'kimetsu no yaiba': 'Demon Slayer - Kimetsu No Yaiba',
    'kingdom': 'Kingdom (2019)',
    'knights of the zodiac': 'Knights Of The Zodiac - Saint Seiya',
    'knights of the zodiac saint seiya': 'Knights Of The Zodiac - Saint Seiya',
    'kung fu the legend continues': 'Kung Fu - The Legend Continues',
    'kupa rashit': 'Cash Register',
    'kuroko no basket': 'Kuroko\'s Basketball',
    'kurokos basketball': 'Kuroko\'s Basketball',
    'kuroko\'s basketball': 'Kuroko\'s Basketball',
    'kuroshitsuji': 'Black Butler',
    'kyle xy': 'Kyle XY',
    'las finest': 'L.A.\'s Finest',
    'l a s finest': 'L.A.\'s Finest',
    'l.a.s finest': 'L.A.\'s Finest',
    'l.a s finest': 'L.A.\'s Finest',
    'l.a. s finest': 'L.A.\'s Finest',
    'larry charles dangerous world of comedy': 'Larry Charles\' Dangerous World Of Comedy',
    'las chicas del cable': 'Cable Girls',
    'law and order': 'Law & Order',
    'law and order criminal intent': 'Law & Order - Criminal Intent',
    'law & order criminal intent': 'Law & Order - Criminal Intent',
    'law and order - criminal intent': 'Law & Order - Criminal Intent',
    'law & order ci': 'Law & Order - Criminal Intent',
    'law and order ci': 'Law & Order - Criminal Intent',
    'law and order los angeles': 'Law & Order - Los Angeles',
    'law & order los angeles': 'Law & Order - Los Angeles',
    'law and order - los angeles': 'Law & Order - Los Angeles',
    'law and order organized crime': 'Law & Order - Organized Crime',
    'law & order organized crime': 'Law & Order - Organized Crime',
    'law and order - organized crime': 'Law & Order - Organized Crime',
    'law and order svu': 'Law & Order - Special Victims Unit',
    'law and order special victims unit': 'Law & Order - Special Victims Unit',
    'law & order svu': 'Law & Order - Special Victims Unit',
    'law & order special victims unit': 'Law & Order - Special Victims Unit',
    'law and order - svu': 'Law & Order - Special Victims Unit',
    'law & order - svu': 'Law & Order - Special Victims Unit',
    'law and order - special victims unit': 'Law & Order - Special Victims Unit',
    'law and order trial by jury': 'Law & Order - Trial By Jury',
    'law & order trial by jury': 'Law & Order - Trial By Jury',
    'law and order - trial by jury': 'Law & Order - Trial By Jury',
    'law and order true crime': 'Law & Order - True Crime',
    'law & order true crime': 'Law & Order - True Crime',
    'law and order - true crime': 'Law & Order - True Crime',
    'law and order uk': 'Law & Order - UK',
    'law & order uk': 'Law & Order - UK',
    'law and order - uk': 'Law & Order - UK',
    'legend of the galactic heroes die neue these': 'Legend Of The Galactic Heroes - Die Neue These',
    'a series of unfortunate events': 'A Series Of Unfortunate Events',
    'lemony snickets a series of unfortunate events': 'A Series Of Unfortunate Events',
    'les misérables': 'Les Miserables (2019)',
    'les miserables': 'Les Miserables (2019)',
    'life': 'Life (2009)',
    'lihiot': 'Beauty And The Baker',
    'lihiot ita': 'Beauty And The Baker',
    'lincoln rhyme': 'Lincoln Rhyme - Hunt For The Bone Collector',
    'lincoln rhyme hunt for the bone': 'Lincoln Rhyme - Hunt For The Bone Collector',
    'lincoln rhyme hunt for the bone collector': 'Lincoln Rhyme - Hunt For The Bone Collector',
    'locke and key': 'Locke & Key',
    'lois & clark': 'Lois And Clark - The New Adventures Of Superman',
    'lois & clark the new adventures of superman': 'Lois And Clark - The New Adventures Of Superman',
    'lois and clark': 'Lois And Clark - The New Adventures Of Superman',
    'lois and clark the new adventures of superman': 'Lois And Clark - The New Adventures Of Superman',
    'lost in space': 'Lost In Space (2018)',
    'lost gold of world war ii': 'Lost Gold Of World War II',
    'louie': 'Louie (2010)',
    'love death and robots': 'Love, Death & Robots',
    'love life': 'Love Life (2020)',
    'love victor': 'Love, Victor',
    'macgyver (2016)': 'MacGyver (2016)',
    'macgyver': 'MacGyver (2016)',
    'magi': 'Magi - The Labyrinth Of Magic',
    'magi the labyrinth of magic': 'Magi - The Labyrinth Of Magic',
    'the magicians': 'The Magicians (2015)',
    'magnum pi': 'Magnum P.I.',
    'magnum p.i': 'Magnum P.I.',
    'maho tsukai no Yome': 'The Ancient Magus\' Bride',
    'mahoutsukai no Yome': 'The Ancient Magus\' Bride',
    'making history': 'Making History (2017)',
    'manhunt unabomber': 'Manhunt',
    'maniac': 'Maniac (2018)',
    'marco polo': 'Marco Polo (2014)',
    'married. with children': 'Married With Children',
    'married... with children': 'Married With Children',
    'mars': 'Mars (2016)',
    'marvels 616': 'Marvel\'s 616',
    'marvel\'s 616': 'Marvel\'s 616',
    '616': 'Marvel\'s 616',
    'agent carter': 'Marvel\'s Agent Carter',
    'marvels agent carter': 'Marvel\'s Agent Carter',
    'marvel\'s agent carter': 'Marvel\'s Agent Carter',
    'agents of s.h.i.e.l.d.': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'marvels agents of shield': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'marvel\'s agents of shield': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'marvels agents of s.h.i.e.l.d': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'marvel\'s agents of s.h.i.e.l.d': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'marvels agents of s.h.i.e.l.d.': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'marvel\'s agents of s.h.i.e.l.d.': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'cloak & dagger': 'Marvel\'s Cloak & Dagger',
    'cloak and dagger': 'Marvel\'s Cloak & Dagger',
    'marvels cloak & dagger': 'Marvel\'s Cloak & Dagger',
    'marvel\'s cloak & dagger': 'Marvel\'s Cloak & Dagger',
    'marvels cloak and dagger': 'Marvel\'s Cloak & Dagger',
    'marvel\'s cloak and dagger': 'Marvel\'s Cloak & Dagger',
    'daredevil': 'Marvel\'s Daredevil',
    'marvels daredevil': 'Marvel\'s Daredevil',
    'marvel\'s daredevil': 'Marvel\'s Daredevil',
    'falcon & winter soldier': 'Marvel\'s Falcon & Winter Soldier',
    'falcon and winter soldier': 'Marvel\'s Falcon & Winter Soldier',
    'marvels falcon & winter soldier': 'Marvel\'s Falcon & Winter Soldier',
    'marvels falcon and winter soldier': 'Marvel\'s Falcon & Winter Soldier',
    'marvel\'s falcon & winter soldier': 'Marvel\'s Falcon & Winter Soldier',
    'marvel\'s falcon and winter soldier': 'Marvel\'s Falcon & Winter Soldier',
    'hawkeye': 'Marvel\'s Hawkeye',
    'marvels hawkeye': 'Marvel\'s Hawkeye',
    'marvel\'s hawkeye': 'Marvel\'s Hawkeye',
    'iron fist': 'Marvel\'s Iron Fist',
    'marvels iron fist': 'Marvel\'s Iron Fist',
    'marvel\'s iron fist': 'Marvel\'s Iron Fist',
    'jessica jones': 'Marvel\'s Jessica Jones',
    'marvels jessica jones': 'Marvel\'s Jessica Jones',
    'marvel\'s jessica jones': 'Marvel\'s Jessica Jones',
    'loki': 'Marvel\'s Loki',
    'marvels loki': 'Marvel\'s Loki',
    'marvel\'s loki': 'Marvel\'s Loki',
    'luke cage': 'Marvel\'s Luke Cage',
    'marvels luke cage': 'Marvel\'s Luke Cage',
    'marvel\'s luke cage': 'Marvel\'s Luke Cage',
    'moon knight': 'Marvel\'s Moon Knight',
    'marvels moon knight': 'Marvel\'s Moon Knight',
    'marvel\'s moon knight': 'Marvel\'s Moon Knight',
    'the defenders': 'Marvel\'s The Defenders',
    'marvels the defenders': 'Marvel\'s The Defenders',
    'marvel\'s the defenders': 'Marvel\'s The Defenders',
    'inhumans': 'Marvel\'s Inhumans',
    'marvels inhumans': 'Marvel\'s Inhumans',
    'marvel\'s inhumans': 'Marvel\'s Inhumans',
    'run': 'Run (2020)',
    'the punisher': 'Marvel\'s The Punisher',
    'marvels the punisher': 'Marvel\'s The Punisher',
    'marvel\'s the punisher': 'Marvel\'s The Punisher',
    'runaways': 'Marvel\'s Runaways',
    'marvels runaways': 'Marvel\'s Runaways',
    'marvel\'s runaways': 'Marvel\'s Runaways',
    'she hulk': 'Marvel\'s She-Hulk',
    'marvels she hulk': 'Marvel\'s She-Hulk',
    'marvel\'s she hulk': 'Marvel\'s She-Hulk',
    'she-hulk': 'Marvel\'s She-Hulk',
    'marvels she-hulk': 'Marvel\'s She-Hulk',
    'marvel\'s she-hulk': 'Marvel\'s She-Hulk',
    'wandavision': 'Marvel\'s WandaVision',
    'marvels wandavision': 'Marvel\'s WandaVision',
    'marvel\'s wandavision': 'Marvel\'s WandaVision',
    'marvels what if': 'Marvel\'s What If...',
    'marvel\'s what if': 'Marvel\'s What If...',
    'mayans': 'Mayans M.C.',
    'mayans mc': 'Mayans M.C.',
    'mayans m.c': 'Mayans M.C.',
    'mayans m.c.': 'Mayans M.C.',
    'mcmafia': 'McMafia',
    'mcmillion': 'McMillion$',
    'mcmillions': 'McMillion$',
    'medici': 'Medici - Masters Of Florence',
    'medici masters of florence': 'Medici - Masters Of Florence',
    'menayek': 'Manayek',
    'messiah': 'Messiah (2020)',
    'metumtemet': 'Dumb',
    'mayonaka no occult koumuin': 'Midnight Occult Civil Servants',
    'midnight texas': 'Midnight, Texas',
    'mixedish': 'Mixed-Ish',
    'mixed-ish': 'Mixed-Ish',
    'monty pythons flying circus': 'Monty Python\'s Flying Circus',
    'mob psycho': 'Mob Psycho 100',
    'the moodys': 'The Moodys (US)',
    'mortal kombat conquest': 'Mortal Kombat - Conquest',
    'mortal kombat defenders of the realm': 'Mortal Kombat - Defenders Of The Realm',
    'mortal kombat legacy': 'Mortal Kombat - Legacy',
    'motherfatherson': 'MotherFatherSon',
    'mother father son': 'MotherFatherSon',
    'motherland fort salem': 'Motherland - Fort Salem',
    'mr mercedes': 'Mr. Mercedes',
    'mr pickles': 'Mr. Pickles',
    'mr robot': 'Mr. Robot',
    'mr sunshine': 'Mr. Sunshine (2018)',
    'mr. sunshine': 'Mr. Sunshine (2018)',
    'mrs america': 'Mrs. America',
    'mrs. america': 'Mrs. America',
    'ms marvel': 'Ms. Marvel',
    'ms. marvel': 'Ms. Marvel',
    'murder she wrote': 'Murder, She Wrote',
    'mythbusters': 'MythBusters',
    'mythic quest': 'Mythic Quest - Raven\'s Banquet',
    'mythic quest ravens banquet': 'Mythic Quest - Raven\'s Banquet',
    'mythic quest raven\'s banquet': 'Mythic Quest - Raven\'s Banquet',
    'nancy drew': 'Nancy Drew (2019)',
    'narcos mexico': 'Narcos - Mexico',
    'nashville': 'Nashville (2012)',
    'ncis': 'NCIS',
    'ncis los angeles': 'NCIS - Los Angeles',
    'ncis - los angeles': 'NCIS - Los Angeles',
    'ncis new orleans': 'NCIS - New Orleans',
    'ncis - new orleans': 'NCIS - New Orleans',
    'new amsterdam': 'New Amsterdam (2018)',
    'newsroom': 'The Newsroom (2012)',
    'next': 'NeXt (2020)',
    'the newsroom': 'The Newsroom (2012)',
    'niptuck': 'NipTuck',
    'nip tuck': 'NipTuck',
    'nos4a2': 'NOS4A2',
    'nurses': 'Nurses (2020)',
    'the oa': 'The OA',
    'the office': 'The Office (US)',
    'o j simpson made in america': 'O.J. - Made In America',
    'o.j. simpson made in america': 'O.J. - Made In America',
    'oj simpson made in america': 'O.J. - Made In America',
    'o j made in america': 'O.J. - Made In America',
    'o.j. made in america': 'O.J. - Made In America',
    'oj made in america': 'O.J. - Made In America',
    'ok ko': 'OK K.O.! Let\'s Be Heroes',
    'ok k o': 'OK K.O.! Let\'s Be Heroes',
    'ok k.o': 'OK K.O.! Let\'s Be Heroes',
    'ok k.o.': 'OK K.O.! Let\'s Be Heroes',
    'ok ko lets be heroes': 'OK K.O.! Let\'s Be Heroes',
    'ok k o lets be heroes': 'OK K.O.! Let\'s Be Heroes',
    'ok k.o lets be heroes': 'OK K.O.! Let\'s Be Heroes',
    'ok k.o. lets be heroes': 'OK K.O.! Let\'s Be Heroes',
    'ok ko - lets be heroes': 'OK K.O.! Let\'s Be Heroes',
    'ok k o - lets be heroes': 'OK K.O.! Let\'s Be Heroes',
    'ok k.o - lets be heroes': 'OK K.O.! Let\'s Be Heroes',
    'ok k.o. - lets be heroes': 'OK K.O.! Let\'s Be Heroes',
    'once upon a time': 'Once Upon A Time (2011)',
    'one day at a time': 'One Day At A Time (2017)',
    'one punch man': 'One-Punch Man',
    'onegai teacher': 'Please Teacher!',
    'onegai teacher!': 'Please Teacher!',
    'please teacher': 'Please Teacher!',
    'our planet': 'Our Planet (2019)',
    'ozzy and jacks world detour': 'Ozzy And Jack\'s World Detour',
    'parades end': 'Parade\'s End',
    'paradise lost': 'Paradise Lost (2020)',
    'paradise pd': 'Paradise PD',
    'parasyte': 'Parasyte - The Maxim',
    'parasyte the maxim': 'Parasyte - The Maxim',
    'party of five': 'Party Of Five (2020)',
    'patriot': 'Patriot (2017)',
    'penguins spy in the huddle': 'Penguins - Spy In The Huddle',
    'penny dreadful city of angels': 'Penny Dreadful - City Of Angels',
    'perry mason': 'Perry Mason (2020)',
    'phantom': 'Phantom - Requiem For The Phantom',
    'phantom requiem for the phantom': 'Phantom - Requiem For The Phantom',
    'philip k dicks electric dreams': 'Philip K. Dick\'s Electric Dreams',
    'philip k dick\'s electric dreams': 'Philip K. Dick\'s Electric Dreams',
    'philip k. dicks electric dreams': 'Philip K. Dick\'s Electric Dreams',
    'ping pong': 'Ping Pong - The Animation',
    'ping pong the animation': 'Ping Pong - The Animation',
    'planet earth ii': 'Planet Earth II',
    'poldark': 'Poldark (2015)',
    'power book ii ghost': 'Power Book II - Ghost',
    'power book ii - ghost': 'Power Book II - Ghost',
    'pretty little liars the perfectionists': 'Pretty Little Liars - The Perfectionists',
    'pride and prejudice': 'Pride And Prejudice (1995)',
    'the protector': 'The Protector (2018)',
    'psycho-pass': 'Psycho-Pass',
    'punky brewster': 'Punky Brewster (2020)',
    'qi': 'QI',
    'raised by wolves': 'Raised By Wolves (2020)',
    'reboot the guardian code': 'ReBoot - The Guardian Code',
    'reno 911': 'Reno 911!',
    'rise': 'Rise (2018)',
    'rizzoli and isles': 'Rizzoli & Isles',
    'r o d': 'R.O.D - Read Or Die',
    'r.o.d': 'R.O.D - Read Or Die',
    'read or die': 'R.O.D - Read Or Die',
    'reign': 'Reign (2013)',
    'roadkill': 'Roadkill (2020)',
    'r.o.d read or die': 'R.O.D - Read Or Die',
    'roots': 'Roots (2016)',
    'roswell new': 'Roswell, New Mexico',
    'roswell new mexico': 'Roswell, New Mexico',
    'satsuriku no tenshi': 'Angels Of Death',
    'saved by the bell': 'Saved By The Bell (2020)',
    'saved by the bell the new class': 'Saved By The Bell - The New Class',
    'saved by the bell the college years': 'Saved By The Bell - The College Years',
    'scandal': 'Scandal (2012)',
    'schitts creek': 'Schitt\'s Creek',
    'search party': 'Search Party (2016)',
    'second chance': 'Second Chance (2016)',
    'self made': 'Self Made - Inspired By The Life Of Madam C.J. Walker',
    'self made inspired by the life of madam cj walker': 'Self Made - Inspired By The Life Of Madam C.J. Walker',
    'self made inspired by the life of madam c.j walker': 'Self Made - Inspired By The Life Of Madam C.J. Walker',
    'self made inspired by the life of madam c.j. walker': 'Self Made - Inspired By The Life Of Madam C.J. Walker',
    'self made inspired by the life of madam c j walker': 'Self Made - Inspired By The Life Of Madam C.J. Walker',
    'self made - inspired by the life of madam cj walker': 'Self Made - Inspired By The Life Of Madam C.J. Walker',
    'self made - inspired by the life of madam c.j walker': 'Self Made - Inspired By The Life Of Madam C.J. Walker',
    'self made - inspired by the life of madam c.j. walker': 'Self Made - Inspired By The Life Of Madam C.J. Walker',
    'self made - inspired by the life of madam c j walker': 'Self Made - Inspired By The Life Of Madam C.J. Walker',
    'shadowhunters the mortal instruments': 'Shadowhunters',
    'shameless': 'Shameless (US)',
    'shameless us': 'Shameless (US)',
    'shangrila': 'Shangri-La (2019)',
    'shangri-la': 'Shangri-La (2019)',
    'shangri la': 'Shangri-La (2019)',
    'shermans showcase': 'Sherman\'s Showcase',
    'shigatsu wa kimi no uso': 'Your Lie In April',
    'siren': 'Siren (2018)',
    'six': 'SIX',
    'smurfs': 'The Smurfs',
    'somali to mori no kamisama': 'Somali And The Forest Spirit',
    'sora yori mo tooi basho': 'A Place Further Than The Universe',
    'soul eater not': 'Soul Eater Not!',
    'spiderman': 'Spider-Man (1994)',
    'spider man': 'Spider-Man (1994)',
    'spider-man': 'Spider-Man (1994)',
    'splitting up together': 'Splitting Up Together (US)',
    'spongebob': 'SpongeBob SquarePants',
    'spongebob squarepants': 'SpongeBob SquarePants',
    'ss': 'SS-GB',
    'ss gb': 'SS-GB',
    'ss-gb': 'SS-GB',
    'star vs the forces of evil': 'Star Vs. The Forces Of Evil',
    'stargate atlantis': 'Stargate Atlantis',
    'stargate origins': 'Stargate - Origins',
    'stargate': 'Stargate SG-1',
    'stargate sg-1': 'Stargate SG-1',
    'stargate sg 1': 'Stargate SG-1',
    'star trek tos': 'Star Trek',
    'star trek (tos)': 'Star Trek',
    'star trek ds9': 'Stark Trek - Deep Space Nine',
    'star trek deep space 9': 'Stark Trek - Deep Space Nine',
    'star trek deep space nine': 'Stark Trek - Deep Space Nine',
    'star trek discovery': 'Star Trek - Discovery',
    'star trek enterprise': 'Star Trek - Enterprise',
    'star trek lower decks': 'Star Trek - Lower Decks',
    'star trek picard': 'Star Trek - Picard',
    'star trek short treks': 'Star Trek - Short Treks',
    'star trek tng': 'Star Trek - The Next Generation',
    'star trek (tng)': 'Star Trek - The Next Generation',
    'star trek the next generation': 'Star Trek - The Next Generation',
    'star trek voyager': 'Star Trek - Voyager',
    'star wars the clone wars': 'Star Wars - The Clone Wars',
    'star wars': 'Star Wars - Rebels',
    'star wars rebels': 'Star Wars - Rebels',
    'star wars resistance': 'Star Wars - Resistance',
    'startup': 'StartUp (2016)',
    'steinsgate': 'Steins;Gate',
    'steins gate': 'Steins;Gate',
    'steinsgate 0': 'Steins;Gate 0',
    'steins gate 0': 'Steins;Gate 0',
    'strangers': 'Strangers (2018)',
    'sunderland til i die': 'Sunderland \'Til I Die',
    'surviving r kelly': 'Surviving R. Kelly',
    'surviving r. kelly': 'Surviving R. Kelly',
    'surviving r.kelly': 'Surviving R. Kelly',
    'swamp thing': 'Swamp Thing (2019)',
    's w a t': 'S.W.A.T. (2017)',
    's.w a t': 'S.W.A.T. (2017)',
    's.w.a t': 'S.W.A.T. (2017)',
    's.w.a.t': 'S.W.A.T. (2017)',
    's.w.a.t.': 'S.W.A.T. (2017)',
    's w a.t.': 'S.W.A.T. (2017)',
    's w.a.t.': 'S.W.A.T. (2017)',
    'sword art online alternative gun gale online': 'Sword Art Online Alternative - Gun Gale Online',
    'taboo': 'Taboo (2017)',
    'tacoma fd': 'Tacoma FD',
    'tacoma f d': 'Tacoma FD',
    'taken': 'Taken (2017)',
    'tate no yuusha no nariagari': 'The Rising Of The Shield Hero',
    'ted bundy falling for a killer': 'Ted Bundy - Falling For A Killer',
    'tell me a story': 'Tell Me A Story (US)',
    'terminator': 'Terminator - The Sarah Connor Chronicles',
    'terminator the sarah connor chronicles': 'Terminator - The Sarah Connor Chronicles',
    'that 70s show': 'That 70\'s Show',
    'that 70\'s show': 'That 70\'s Show',
    'the adventures of jimmy neutron boy genius': 'The Adventures Of Jimmy Neutron - Boy Genius',
    'the code': 'The Code (2019)',
    'the continental': 'The Continental (2021)',
    'the dictators playbook': 'The Dictator\'s Playbook',
    'the dictator\'s playbook': 'The Dictator\'s Playbook',
    'the forgotten army': 'The Forgotten Army - Azaadi Ke Liye',
    'the forgotten army azaadi ke liye': 'The Forgotten Army - Azaadi Ke Liye',
    'the i land': 'The I-Land',
    'the i-land': 'The I-Land',
    'the last og': 'The Last O.G.',
    'the last o.g': 'The Last O.G.',
    'the last o.g.': 'The Last O.G.',
    'the librarians': 'The Librarians (2014)',
    'marvelous mrs maisel': 'The Marvelous Mrs. Maisel',
    'marvelous mrs. maisel': 'The Marvelous Mrs. Maisel',
    'the marvelous mrs maisel': 'The Marvelous Mrs. Maisel',
    'the mind explained': 'The Mind, Explained',
    'the oc': 'The O.C.',
    'the o.c': 'The O.C.',
    'the o.c.': 'The O.C.',
    'the o c': 'The O.C.',
    'the other one': 'The Other One (2020)',
    'the outsider': 'The Outsider (2020)',
    'the planets': 'The Planets (2019)',
    'the planets uk': 'The Planets (2019)',
    'the politician': 'The Politician (2019)',
    'the queens gambit': 'The Queen\'s Gambit',
    'the queen\'s gambit': 'The Queen\'s Gambit',
    'the ranch': 'The Ranch (2016)',
    'the stand': 'The Stand (2020)',
    'the stranger': 'The Stranger (2020)',
    'the tick': 'The Tick (2016)',
    'the tomorrow people': 'The Tomorrow People (US)',
    'the victims game': 'The Victim\'s Game',
    'the victim\'s game': 'The Victim\'s Game',
    'the walking dead world beyond': 'The Walking Dead - World Beyond',
    'the watch': 'The Watch (2020)',
    'this is': 'This Is Us',
    'tiger king': 'Tiger King - Murder, Mayhem And Madness',
    'tiger king murder mayhem and madness': 'Tiger King - Murder, Mayhem And Madness',
    'tiger king - murder mayhem and madness': 'Tiger King - Murder, Mayhem And Madness',
    'tiger king murder, mayhem and madness': 'Tiger King - Murder, Mayhem And Madness',
    'timeless': 'Timeless (2016)',
    'titans': 'Titans (2018)',
    'tom clancys jack ryan': 'Tom Clancy\'s Jack Ryan',
    'touch': 'Touch (2012)',
    'travelers': 'Travelers (2016)',
    'troy fall of a city': 'Troy - Fall Of A City',
    'trump an american dream': 'Trump - An American Dream',
    'trust': 'Trust (2018)',
    'trust me': 'Trust Me (2017)',
    'tuca and bertie': 'Tuca & Bertie',
    'turn': 'TURN - Washington\'s Spies',
    'turn washingtons spies': 'TURN - Washington\'s Spies',
    'turn - washingtons spies': 'TURN - Washington\'s Spies',
    'turn washington\'s spies': 'TURN - Washington\'s Spies',
    'turn - washington\'s spies': 'TURN - Washington\'s Spies',
    'the twilight zone': 'The Twilight Zone (2019)',
    'tzel shel emet': 'Shadow Of Truth',
    'undertaker the last ride': 'Undertaker - The Last Ride',
    'wwe undertaker the last ride': 'Undertaker - The Last Ride',
    'unreal': 'UnREAL',
    'unsolved': 'Unsolved - The Murders Of Tupac And The Notorious B.I.G.',
    'unsolved the murders of tupac and the notorious big': 'Unsolved - The Murders Of Tupac And The Notorious B.I.G.',
    'unsolved the murders of tupac and the notorious b.i.g.':
        'Unsolved - The Murders Of Tupac And The Notorious B.I.G.',
    'unsolved - the murders of tupac and the notorious big': 'Unsolved - The Murders Of Tupac And The Notorious B.I.G.',
    'unsolved - the murders of tupac and the notorious b.i.g':
        'Unsolved - The Murders Of Tupac And The Notorious B.I.G.',
    'unsolved mysteries': 'Unsolved Mysteries (2020)',
    'utopia': 'Utopia (2020)',
    'unwell': '(Un)Well',
    'unxplained': 'The UnXplained',
    'the unxplained': 'The UnXplained',
    'v': 'V (2009)',
    'van der valk': 'Van Der Valk (2020)',
    'the venture bros': 'The Venture Bros.',
    'vice': 'VICE',
    'the vietnam war': 'The Vietnam War (2017)',
    'vis a vis': 'Locked Up',
    'walker': 'Walker, Texas Ranger',
    'walker texas ranger': 'Walker, Texas Ranger',
    'warrior': 'Warrior (2019)',
    'watership down': 'Watership Down (2018)',
    'welcome to': 'Welcome To Sweden (2014)',
    'welcome to sweden': 'Welcome To Sweden (2014)',
    'what if': 'What - If',
    'whats my name': 'What\'s My Name - Muhammad Ali',
    'whats my name muhammad ali': 'What\'s My Name - Muhammad Ali',
    'when they see': 'When They See Us',
    'whitest kids u know': 'The Whitest Kids U\'Know',
    'the whitest kids u know': 'The Whitest Kids U\'Know',
    'wilfred': 'Wilfred (US)',
    'will and grace': 'Will & Grace',
    'workin moms': 'Workin\' Moms',
    'world war ii in': 'World War II In HD Colour',
    'world war ii in hd colour': 'World War II In HD Colour',
    'the worlds most extraordinary homes': 'The World\'s Most Extraordinary Homes',
    'wormwood': 'Wormwood (2017)',
    'wrecked': 'Wrecked (2016)',
    'wu assassins': 'WU Assassins',
    'wu tang': 'Wu-Tang - An American Saga',
    'wu-tang': 'Wu-Tang - An American Saga',
    'wu tang an american saga': 'Wu-Tang - An American Saga',
    'wu-tang an american saga': 'Wu-Tang - An American Saga',
    'the x files': 'The X-Files',
    'x men': 'X-Men - The Animated Series',
    'x men the animated series': 'X-Men - The Animated Series',
    'xena': 'Xena - Warrior Princess',
    'xena warrior princess': 'Xena - Warrior Princess',
    'yakusoku no neverland': 'The Promised Neverland',
    'yellowstone': 'Yellowstone (2018)',
    'you': 'YOU',
    'youre the worst': 'You\'re The Worst',
    'zaguri imperya': 'Zaguri Empire',
    'zero zero zero': 'ZeroZeroZero',
    'zerozerozero': 'ZeroZeroZero',
    'zetsuen no tempest': 'Blast Of Tempest',
    'zoeys extraordinary playlist': 'Zoey\'s Extraordinary Playlist'
}
