SHOWS_MAP = {
    '1971': '1971 - The Year That Music Changed Everything',
    '1971 the year that music changed everything': '1971 - The Year That Music Changed Everything',
    'the year that music changed everything': '1971 - The Year That Music Changed Everything',
    '24 legacy': '24 - Legacy',
    '3%': '3 Percent',
    '3below': '3Below - Tales Of Arcadia',
    '3below tales of arcadia': '3Below - Tales Of Arcadia',
    '7seeds': '7Seeds',
    '911': '9-1-1',
    '9 1 1': '9-1-1',
    '911 lone star': '9-1-1 - Lone Star',
    '9-1-1 lone star': '9-1-1 - Lone Star',
    '9 1 1 lone star': '9-1-1 - Lone Star',
    'a team': 'The A-Team',
    'a-team': 'The A-Team',
    'the a team': 'The A-Team',
    'the a-team': 'The A-Team',
    'the abc murders': 'The ABC Murders',
    'abstract': 'Abstract - The Art Of Design',
    'abstract the art of design': 'Abstract - The Art Of Design',
    'adventure time with finn and jake': 'Adventure Time',
    'a i the end of humanity': 'A.I. - The End Of Humanity',
    'a.i the end of humanity': 'A.I. - The End Of Humanity',
    'a.i. the end of humanity': 'A.I. - The End Of Humanity',
    'a i - the end of humanity': 'A.I. - The End Of Humanity',
    'a.i - the end of humanity': 'A.I. - The End Of Humanity',
    'a.i. - the end of humanity': 'A.I. - The End Of Humanity',
    'akame ga kill': 'Akame Ga Kill!',
    'al haspektrum': 'On The Spectrum',
    'aldnoah.zero': 'Aldnoah.Zero',
    'aldnoah zero': 'Aldnoah.Zero',
    'alex inc': 'Alex, Inc.',
    'alex, inc': 'Alex, Inc.',
    'alex inc.': 'Alex, Inc.',
    'all american': 'All American (2018)',
    'all creatures great and small': 'All Creatures Great And Small (2020)',
    'all or nothing manchester city': 'All Or Nothing - Manchester City',
    'all or nothing new zealand all blacks': 'All Or Nothing - New Zealand All Blacks',
    'all or nothing tottenham hotspur': 'All Or Nothing - Tottenham Hotspur',
    'allen v farrow': 'Allen V. Farrow',
    'allen v. farrow': 'Allen V. Farrow',
    'ally mcbeal': 'Ally McBeal',
    'alta mar': 'High Seas',
    'alto mar': 'High Seas',
    'american dad': 'American Dad!',
    'the americans': 'The Americans (2013)',
    'amazing stories': 'Amazing Stories (2020)',
    'angel beats': 'Angel Beats!',
    'animal kingdom': 'Animal Kingdom (2016)',
    'animals': 'Animals.',
    'ano hi mita hana': 'Anohana - The Flower We Saw That Day',
    'another life': 'Another Life (2019)',
    'ap bio': 'A.P. BIO',
    'a p bio': 'A.P. BIO',
    'a.p bio': 'A.P. BIO',
    'a.p. bio': 'A.P. BIO',
    'aquarius': 'Aquarius (2015)',
    'aquarius us': 'Aquarius (2015)',
    'archer': 'Archer (2009)',
    'ash vs evil dead': 'Ash Vs. Evil Dead',
    'avatar': 'Avatar - The Last Airbender',
    'avatar the last airbender': 'Avatar - The Last Airbender',
    'awkward': 'Awkward.',
    'baki': 'Baki (2018)',
    'barbarians': 'Barbarians (2020)',
    'batman': 'Batman - The Animated Series',
    'batman the animated series': 'Batman - The Animated Series',
    'battlebots': 'BattleBots (2015)',
    'battlestar galactica': 'Battlestar Galactica (2003)',
    'beauty and the beast': 'Beauty And The Beast (2012)',
    'beavis and butthead': 'Beavis And Butt-Head',
    'beavis and butt-head': 'Beavis And Butt-Head',
    'bein arizona lnes ziona': 'Between Arizona And Nes Ziona',
    'being human': 'Being Human (US)',
    'betipul': 'In Therapy',
    'beverly hills': 'Beverly Hills, 90210',
    'beverly hills 90210': 'Beverly Hills, 90210',
    'bh90210': 'BH90210',
    'bh 90210': 'BH90210',
    'big sky': 'Big Sky (2020)',
    'blackaf': 'BlackAF',
    'black af': 'BlackAF',
    'blackish': 'Black-Ish',
    'black-ish': 'Black-Ish',
    'the blacklist redemption': 'The Blacklist - Redemption',
    'blackspace': 'BlackSpace',
    'black space': 'BlackSpace',
    'blood and treasure': 'Blood & Treasure',
    'bloodlands': 'Bloodlands (2021)',
    'blue planet ii': 'Blue Planet II',
    'bobs burgers': 'Bob\'s Burgers',
    'bob\'s burgers': 'Bob\'s Burgers',
    'bodyguard': 'Bodyguard (2018)',
    'boku dake ga inai machi': 'ERASED',
    'boku no hero academia': 'My Hero Academia',
    'boruto': 'Boruto – Naruto Next Generations',
    'boruto naruto next generations': 'Boruto – Naruto Next Generations',
    'braindead': 'BrainDead',
    'brave new world': 'Brave New World (2020)',
    'breakfast lunch and dinner': 'Breakfast, Lunch & Dinner',
    'breakfast lunch & dinner': 'Breakfast, Lunch & Dinner',
    'breakfast, lunch and dinner': 'Breakfast, Lunch & Dinner',
    'the bridge': 'The Bridge (2011)',
    'brooklyn nine nine': 'Brooklyn Nine-Nine',
    'btooom': 'BTOOOM!',
    'btooom!': 'BTOOOM!',
    'buffy': 'Buffy - The Vampire Slayer',
    'buffy the vampire slayer': 'Buffy - The Vampire Slayer',
    'bull': 'Bull (2016)',
    'call my agent': 'Call My Agent!',
    'cant get you out of my head': 'Can\'t Get You Out Of My Head',
    'carols second act': 'Carol\'s Second Act',
    'castle': 'Castle (2009)',
    'catastrophe': 'Catastrophe (2015)',
    'catch 22': 'Catch-22',
    'catch and kill': 'Catch And Kill - The Podcast Tapes',
    'catch and kill the podcast tapes': 'Catch And Kill - The Podcast Tapes',
    'la catedral del mar': 'Cathedral Of The Sea',
    'chambers': 'Chambers (2019)',
    'chappelles show': 'Chappelle\'s Show',
    'chappelle\'s show': 'Chappelle\'s Show',
    'charmed': 'Charmed (2018)',
    'cheer': 'Cheer (2020)',
    'chefs table': 'Chef\'s Table',
    'chef\'s table': 'Chef\'s Table',
    'chefs table france': 'Chef\'s Table - France',
    'chef\'s table france': 'Chef\'s Table - France',
    'chi fire': 'Chicago Fire',
    'chi med': 'Chicago Med',
    'chi pd': 'Chicago P.D.',
    'chicago pd': 'Chicago P.D.',
    'chicago p d': 'Chicago P.D.',
    'chicago p.d': 'Chicago P.D.',
    'chicago p.d.': 'Chicago P.D.',
    'children of dune': 'Frank Herbert\'s Children Of Dune',
    'the chilling adventures of sabrina': 'Chilling Adventures Of Sabrina',
    'citizen p i': 'Citizen P.I.',
    'citizen pi': 'Citizen P.I.',
    'clarksons farm': 'Clarkson\'s Farm',
    'cobra': 'COBRA (2020)',
    'cocomelon': 'CoComelon',
    'code geass': 'Code Geass - Lelouch Of The Rebellion',
    'code geass lelouch of the rebellion': 'Code Geass - Lelouch Of The Rebellion',
    'connected': 'Connected (2020)',
    'connecting': 'Connecting...',
    'crashing': 'Crashing (2017)',
    'crazy ex girlfriend': 'Crazy Ex-Girlfriend',
    'crazy ex-girlfriend': 'Crazy Ex-Girlfriend',
    'frank herberts children of dune': 'Frank Herbert\'s Children Of Dune',
    'frank herbert\'s children of dune': 'Frank Herbert\'s Children Of Dune',
    'dune': 'Frank Herbert\'s Dune',
    'frank herberts dune': 'Frank Herbert\'s Dune',
    'frank herbert\'s dune': 'Frank Herbert\'s Dune',
    'cocaine cowboys the kings of miami': 'Cocaine Cowboys - The Kings Of Miami',
    'conversations with a killer the ted bundy tapes': 'Conversations With A Killer - The Ted Bundy Tapes',
    'cosmos a spacetime odyssey': 'Cosmos (2014)',
    'coyote': 'Coyote (2021)',
    'criminal minds beyond borders': 'Criminal Minds - Beyond Borders',
    'criminal uk': 'Criminal - United Kingdom',
    'criminal united kingdom': 'Criminal - United Kingdom',
    'cursed': 'Cursed (2020)',
    'da vincis demons': 'Da Vinci\'s Demons',
    'da vinci\'s demons': 'Da Vinci\'s Demons',
    'dark': 'DARK',
    'the dark crystal age of resistance': 'The Dark Crystal - Age Of Resistance',
    'darling in the franxx': 'Darling In The FranXX',
    'danmachi': 'Is It Wrong To Try To Pick Up Girls In A Dungeon',
    'dungeon ni deai wo motomeru no wa machigatteiru darou ka': 'Is It Wrong To Try To Pick Up Girls In A Dungeon',
    'dark side of the 90s': 'Dark Side Of The 90s',
    'darwins game': 'Darwin\'s Game',
    'darwin\'s game': 'Darwin\'s Game',
    'dash and lily': 'Dash & Lily',
    'dave': 'DAVE',
    'dawsons creek': 'Dawson\'s Creek',
    'dawson\'s creek': 'Dawson\'s Creek',
    'dcs legends of tomorrow': 'DC\'s Legends Of Tomorrow',
    'dc\'s legends of tomorrow': 'DC\'s Legends Of Tomorrow',
    'legends of tomorrow': 'DC\'s Legends Of Tomorrow',
    'dear': 'Dear...',
    'deception': 'Deception (2018)',
    'descendants wicked world': 'Descendants - Wicked World',
    'dexters lab': 'Dexter\'s Lab',
    'dexter\'s lab': 'Dexter\'s Lab',
    'dirk gentlys holistic detective agency': 'Dirk Gently\'s Holistic Detective Agency',
    'dirk gently\'s holistic detective agency': 'Dirk Gently\'s Holistic Detective Agency',
    'disney gallery the mandalorian': 'Disney Gallery - Star Wars - The Mandalorian',
    'disney gallery star wars the mandalorian': 'Disney Gallery - Star Wars - The Mandalorian',
    'divorce': 'Divorce (2016)',
    'divorce us': 'Divorce (2016)',
    'doctor who': 'Doctor Who (2005)',
    'documentary now': 'Documentary Now!',
    'dont fuck with cats': 'Don\'t F**k With Cats - Hunting An Internet Killer',
    'dont f**k with cats': 'Don\'t F**k With Cats - Hunting An Internet Killer',
    'dont fuck with cats hunting an internet killer': 'Don\'t F**k With Cats - Hunting An Internet Killer',
    'dont f**k with cats hunting an internet killer': 'Don\'t F**k With Cats - Hunting An Internet Killer',
    'dont fuck with cats - hunting an internet killer': 'Don\'t F**k With Cats - Hunting An Internet Killer',
    'dont f**k with cats - hunting an internet killer': 'Don\'t F**k With Cats - Hunting An Internet Killer',
    'dont trust the b---- in apartment 23': 'Don\'t Trust The B---- In Apartment 23',
    'dont trust the bitch in apartment 23': 'Don\'t Trust The B---- In Apartment 23',
    'dororo': 'Dororo (2019)',
    'dota dragons blood': 'DOTA - Dragon\'s Blood',
    'dr death': 'Dr. Death',
    'dr death the undoctored story': 'Dr. Death - The Undoctored Story',
    'dr. death the undoctored story': 'Dr. Death - The Undoctored Story',
    'dr stone': 'Dr. Stone',
    'dracula': 'Dracula (2020)',
    'dragon ball gt': 'Dragon Ball GT',
    'dragon ball heroes': 'Super Dragon Ball Heroes',
    'dynasties uk': 'Dynasties (2018)',
    'dynasties': 'Dynasties (2018)',
    'dynasty': 'Dynasty (2017)',
    'eden': 'Eden (2021) (AU)',
    'eden untamed planet': 'Eden - Untamed Planet',
    'ehad al ehad': 'One On One',
    'emergency call': 'Emergency Call (US)',
    'empire': 'Empire (2015)',
    'erased': 'Erased (2017)',
    'euphoria': 'Euphoria (US)',
    'everythings gonna be okay': 'Everything\'s Gonna Be Okay',
    'everything sucks': 'Everything Sucks!',
    'evil genius': 'Evil Genius - The True Story Of America\'s Most Diabolical Bank Heist',
    'evil genius the true story of americas most diabolical bank heist':
        'Evil Genius - The True Story Of America\'s Most Diabolical Bank Heist',
    'evil genius the true story of america\'s most diabolical bank heist':
        'Evil Genius - The True Story Of America\'s Most Diabolical Bank Heist',
    'extinct': 'Extinct (2017)',
    'fantasy island': 'Fantasy Island (2021)',
    'fateapocrypha': 'Fate - Apocrypha',
    'fate apocrypha': 'Fate - Apocrypha',
    'fategrand order': 'Fate - Grand Order',
    'fate grand order': 'Fate - Grand Order',
    'fategrand order absolute demonic front babylonia': 'Fate - Grand Order - Absolute Demonic Front - Babylonia',
    'fate grand order absolute demonic front babylonia': 'Fate - Grand Order - Absolute Demonic Front - Babylonia',
    'fategrand order absolute demonic front - babylonia': 'Fate - Grand Order - Absolute Demonic Front - Babylonia',
    'fate grand order absolute demonic front - babylonia': 'Fate - Grand Order - Absolute Demonic Front - Babylonia',
    'fategrand order - absolute demonic front babylonia': 'Fate - Grand Order - Absolute Demonic Front - Babylonia',
    'fate grand order - absolute demonic front babylonia': 'Fate - Grand Order - Absolute Demonic Front - Babylonia',
    'fategrand order - absolute demonic front - babylonia': 'Fate - Grand Order - Absolute Demonic Front - Babylonia',
    'fate grand order - absolute demonic front - babylonia': 'Fate - Grand Order - Absolute Demonic Front - Babylonia',
    'fatekaleid liner prisma illya': 'Fate - Kaleid Liner Prisma Illya',
    'fate kaleid liner prisma illya': 'Fate - Kaleid Liner Prisma Illya',
    'fatestay night': 'Fate - Stay Night',
    'fate stay night': 'Fate - Stay Night',
    'fatestay night unlimited blade works': 'Fate - Stay Night - Unlimited Blade Works',
    'fate stay night unlimited blade works': 'Fate - Stay Night - Unlimited Blade Works',
    'fatezero': 'Fate - Zero',
    'fate zero': 'Fate - Zero',
    'fate the winx saga': 'Fate - The Winx Saga',
    'the winx saga': 'Fate - The Winx Saga',
    'fbi': 'FBI',
    'fbi most wanted': 'FBI - Most Wanted',
    'fbi - most wanted': 'FBI - Most Wanted',
    'filthy rich': 'Filthy Rich (US)',
    'the flash': 'The Flash (2014)',
    'flashforward': 'FlashForward',
    'flesh and blood': 'Flesh And Blood (2020)',
    'food wars': 'Food Wars! Shokugeki No Soma',
    'food wars shokugeki no soma': 'Food Wars! Shokugeki No Soma',
    'food wars - shokugeki no soma': 'Food Wars! Shokugeki No Soma',
    'shokugeki no soma': 'Food Wars! Shokugeki No Soma',
    'foot wave': '100 Foot Wave',
    'for the people': 'For The People (2018)',
    'foundation': 'Foundation (2020)',
    'frontier': 'Frontier (2016)',
    'forensic files ii': 'Forensic Files II',
    'forever': 'Forever (2014)',
    'formula 1': 'Formula 1 - Drive To Survive',
    'formula 1 drive to survive': 'Formula 1 - Drive To Survive',
    'drive to survive': 'Formula 1 - Drive To Survive',
    'formula 1 the race to perfection': 'Race To Perfection',
    'the fosters': 'The Fosters (2013)',
    'freezing': 'Freezing (2011)',
    'fresh fried and crispy': 'Fresh, Fried & Crispy',
    'fresh, fried and crispy': 'Fresh, Fried & Crispy',
    'fresh fried & crispy': 'Fresh, Fried & Crispy',
    'the fresh prince of bel air': 'The Fresh Prince Of Bel-Air',
    'the fugitive': 'The Fugitive (2020)',
    'fullmetal alchemist brotherhood': 'Fullmetal Alchemist - Brotherhood',
    'gabbys dollhouse': 'Gabby\'s Dollhouse',
    'generation': 'Genera+ion',
    'genius': 'Genius (2017)',
    'ghostwriter': 'Ghostwriter (2019)',
    'gilmore girls a year in the life': 'Gilmore Girls - A Year In The Life',
    'gin no saji': 'Silver Spoon',
    'ginny and georgia': 'Ginny & Georgia',
    'girls5eva': 'Girls5eva',
    'ghost in the shell arise alternative architecture': 'Ghost In The Shell - Arise - Alternative Architecture',
    'ghost in the shell stand alone complex': 'Ghost In The Shell - Stand Alone Complex',
    'ghosts': 'Ghosts (2019)',
    'glitch': 'Glitch (2015)',
    'glow': 'GLOW',
    'goblin slayer': 'GOBLIN SLAYER',
    'godless': 'Godless (2017)',
    'gold rush winters fortune': 'Gold Rush: Winter\'s Fortune',
    'the goldbergs': 'The Goldbergs (2013)',
    'gordon ramsay uncharted': 'Gordon Ramsay - Uncharted',
    'gossip girl': 'Gossip Girl (2021)',
    'grand hotel': 'Grand Hotel (US)',
    'the grand tour': 'The Grand Tour (2016)',
    'greatest events of world war ii in': 'Greatest Events Of WWII In Colour',
    'greatest events of world war ii in colour': 'Greatest Events Of WWII In Colour',
    'greatest events of world war ii in hd colour': 'Greatest Events Of WWII In Colour',
    'greatest events of wwii in colour': 'Greatest Events Of WWII In Colour',
    'greys anatomy': 'Grey\'s Anatomy',
    'grey\'s anatomy': 'Grey\'s Anatomy',
    'grownish': 'Grown-Ish',
    'grown-ish': 'Grown-Ish',
    'haachayot hamutzlachot sheli': 'Sisters',
    'ha\'achayot hamutzlachot sheli': 'Sisters',
    'haborer': 'HaBorer',
    'hacks': 'Hacks (2021)',
    'hagure yuusha no estetica': 'Aesthetica Of A Rogue Hero',
    'haikyuu': 'Haikyuu!!',
    'haikyuu!': 'Haikyuu!!',
    'hajime no ippo new challenger': 'Hajime No Ippo - New Challenger',
    'hajime no ippo rising': 'Hajime No Ippo - Rising',
    'halston': 'HALSTON',
    'hamefakedet': 'Dismissed',
    'the handmaids tale': 'The Handmaid\'s Tale',
    'the handmaid\'s tale': 'The Handmaid\'s Tale',
    'haparlament': 'The Parliament (Haparlament)',
    'happy': 'Happy!',
    'harmonquest': 'HarmonQuest',
    'hatabach': 'The Chef (2020)',
    'hataraku saibou': 'Cells At Work!',
    'hatufim': 'Prisoners Of War',
    'hawaii 5-0': 'Hawaii Five-0',
    'hawaii five-o': 'Hawaii Five-0',
    'hazarot': 'Rehearsals',
    'heartland': 'Heartland (2007) (CA)',
    'heartland ca': 'Heartland (2007) (CA)',
    'heist': 'Heist (2021)',
    'hercules': 'Hercules - The Legendary Journeys',
    'hercules the legendary journeys': 'Hercules - The Legendary Journeys',
    'here and now': 'Here And Now (2018)',
    'high maintenance': 'High Maintenance (2016)',
    'high on the hog': 'High On The Hog - How African American Cuisine Transformed America',
    'high on the hog how african american cuisine transformed america':
        'High On The Hog - How African American Cuisine Transformed America',
    'high school musical the musical the series': 'High School Musical - The Musical - The Series',
    'hillary': 'Hillary (2020)',
    'hit and run': 'Hit & Run',
    'hitlers circle of evil': 'Hitler\'s Circle Of Evil',
    'hollywood': 'Hollywood (2020)',
    'home movie the princess bride': 'Home Movie - The Princess Bride',
    'house of cards': 'House Of Cards (US)',
    'hubble': 'Hubble - A Look Into The Universe',
    'hubble a look into the universe': 'Hubble - A Look Into The Universe',
    'hunter x hunter': 'Hunter X Hunter (2011)',
    'hunters': 'Hunters (2020)',
    'icarly': 'ICarly (2021)',
    'ill be gone in the dark': 'I\'ll Be Gone In The Dark',
    'i\'ll be gone in the dark': 'I\'ll Be Gone In The Dark',
    'immigration nation': 'Immigration Nation (2020)',
    'in the dark': 'In The Dark (2019)',
    'the inbetween': 'The InBetween',
    'innocent': 'Innocent (2018)',
    'the innocent man': 'The Innocent Man (2018)',
    'intelligence': 'Intelligence (2020)',
    'inside bills brain decoding bill gates': 'Inside Bill\'s Brain - Decoding Bill Gates',
    'inside bill\'s brain decoding bill gates': 'Inside Bill\'s Brain - Decoding Bill Gates',
    'inside bills brain - decoding bill gates': 'Inside Bill\'s Brain - Decoding Bill Gates',
    'inside bill\'s brain - decoding bill gates': 'Inside Bill\'s Brain - Decoding Bill Gates',
    'instinct': 'Instinct (2018)',
    'inuyasha': 'InuYasha',
    'inu yasha': 'InuYasha',
    'invincible': 'Invincible (2021)',
    'ish hashuv meod': 'Very Important Person',
    'the it crowd': 'The IT Crowd',
    'its a sin': 'It\'s A Sin',
    'its always sunny in philadelphia': 'It\'s Always Sunny In Philadelphia',
    'it\'s always sunny in philadelphia': 'It\'s Always Sunny In Philadelphia',
    'its okay to not be okay': 'It\'s Okay To Not Be Okay',
    'its ok to not be ok': 'It\'s Okay To Not Be Okay',
    'izombie': 'iZombie',
    'james clavells shogun': 'James Clavell\'s Shogun',
    'james clavell\'s shogun': 'James Clavell\'s Shogun',
    'shogun': 'James Clavell\'s Shogun',
    'jean claude van johnson': 'Jean-Claude Van Johnson',
    'jean-claude van johnson': 'Jean-Claude Van Johnson',
    'jeffrey epstein': 'Jeffrey Epstein - Filthy Rich',
    'jeffrey epstein filthy rich': 'Jeffrey Epstein - Filthy Rich',
    'jellystone': 'Jellystone!',
    'jericho': 'Jericho (2006)',
    'jerusalem city of faith and fury': 'Jerusalem - City Of Faith And Fury',
    'the jinx': 'The Jinx - The Life And Deaths Of Robert Durst',
    'the jinx the life and deaths of robert durst': 'The Jinx - The Life And Deaths Of Robert Durst',
    'jojos bizarre adventure': 'JoJo\'s Bizarre Adventure (2012)',
    'jojo\'s bizarre adventure': 'JoJo\'s Bizarre Adventure (2012)',
    'jonathan strange & mr norrell': 'Jonathan Strange And Mr. Norrell',
    'jonathan strange & mr. norrell': 'Jonathan Strange And Mr. Norrell',
    'jonathan strange and mr norrell': 'Jonathan Strange And Mr. Norrell',
    'jonathan strange and mr. norrell': 'Jonathan Strange And Mr. Norrell',
    'jupiters legacy': 'Jupiter\'s Legacy',
    'jurassic world camp cretaceous': 'Jurassic World - Camp Cretaceous',
    'kacha ze': 'Significant Other',
    'kevin can f... himself': 'Kevin Can F**k Himself',
    'kevin can fk himself': 'Kevin Can F**k Himself',
    'kevin can fuck himself': 'Kevin Can F**k Himself',
    'kevin (probably) saves the world': 'Kevin (Probably) Saves The World',
    'kevin probably saves the world': 'Kevin (Probably) Saves The World',
    'kevin saves the world': 'Kevin (Probably) Saves The World',
    'kfulim': 'False Flag',
    'the killing': 'The Killing (2011)',
    'kimetsu no yaiba': 'Demon Slayer - Kimetsu No Yaiba',
    'kingdom': 'Kingdom (2019)',
    'knights of the zodiac': 'Knights Of The Zodiac - Saint Seiya',
    'knights of the zodiac saint seiya': 'Knights Of The Zodiac - Saint Seiya',
    'kung fu': 'Kung Fu (2021)',
    'kung fu the legend continues': 'Kung Fu - The Legend Continues',
    'kupa rashit': 'Cash Register',
    'kuroko no basket': 'Kuroko\'s Basketball',
    'kurokos basketball': 'Kuroko\'s Basketball',
    'kuroko\'s basketball': 'Kuroko\'s Basketball',
    'kuroshitsuji': 'Black Butler',
    'kvodo': 'Your Honor',
    'kyle xy': 'Kyle XY',
    'las finest': 'L.A.\'s Finest',
    'l a s finest': 'L.A.\'s Finest',
    'l.a.s finest': 'L.A.\'s Finest',
    'l.a s finest': 'L.A.\'s Finest',
    'l.a. s finest': 'L.A.\'s Finest',
    'larry charles dangerous world of comedy': 'Larry Charles\' Dangerous World Of Comedy',
    'las chicas del cable': 'Cable Girls',
    'law and order': 'Law & Order',
    'law and order criminal intent': 'Law & Order - Criminal Intent',
    'law & order criminal intent': 'Law & Order - Criminal Intent',
    'law and order - criminal intent': 'Law & Order - Criminal Intent',
    'law & order ci': 'Law & Order - Criminal Intent',
    'law and order ci': 'Law & Order - Criminal Intent',
    'law and order los angeles': 'Law & Order - Los Angeles',
    'law & order los angeles': 'Law & Order - Los Angeles',
    'law and order - los angeles': 'Law & Order - Los Angeles',
    'law and order organized crime': 'Law & Order - Organized Crime',
    'law & order organized crime': 'Law & Order - Organized Crime',
    'law and order - organized crime': 'Law & Order - Organized Crime',
    'law and order svu': 'Law & Order - Special Victims Unit',
    'law and order special victims unit': 'Law & Order - Special Victims Unit',
    'law & order svu': 'Law & Order - Special Victims Unit',
    'law & order special victims unit': 'Law & Order - Special Victims Unit',
    'law and order - svu': 'Law & Order - Special Victims Unit',
    'law & order - svu': 'Law & Order - Special Victims Unit',
    'law and order - special victims unit': 'Law & Order - Special Victims Unit',
    'law and order trial by jury': 'Law & Order - Trial By Jury',
    'law & order trial by jury': 'Law & Order - Trial By Jury',
    'law and order - trial by jury': 'Law & Order - Trial By Jury',
    'law and order true crime': 'Law & Order - True Crime',
    'law & order true crime': 'Law & Order - True Crime',
    'law and order - true crime': 'Law & Order - True Crime',
    'law and order uk': 'Law & Order - UK',
    'law & order uk': 'Law & Order - UK',
    'law and order - uk': 'Law & Order - UK',
    'legend of the galactic heroes die neue these': 'Legend Of The Galactic Heroes - Die Neue These',
    'a series of unfortunate events': 'A Series Of Unfortunate Events',
    'lemony snickets a series of unfortunate events': 'A Series Of Unfortunate Events',
    'les misérables': 'Les Miserables (2019)',
    'les miserables': 'Les Miserables (2019)',
    'leverage redemption': 'Leverage - Redemption',
    'life': 'Life (2009)',
    'liga gimel': 'The Last League',
    'lihiot': 'Beauty And The Baker',
    'lihiot ita': 'Beauty And The Baker',
    'lincoln rhyme': 'Lincoln Rhyme - Hunt For The Bone Collector',
    'lincoln rhyme hunt for the bone': 'Lincoln Rhyme - Hunt For The Bone Collector',
    'lincoln rhyme hunt for the bone collector': 'Lincoln Rhyme - Hunt For The Bone Collector',
    'liseys story': 'Lisey\'s Story',
    'locke and key': 'Locke & Key',
    'lohamim': 'Fighters',
    'lois & clark': 'Lois And Clark - The New Adventures Of Superman',
    'lois & clark the new adventures of superman': 'Lois And Clark - The New Adventures Of Superman',
    'lois and clark': 'Lois And Clark - The New Adventures Of Superman',
    'lois and clark the new adventures of superman': 'Lois And Clark - The New Adventures Of Superman',
    'lost in space': 'Lost In Space (2018)',
    'lost gold of world war ii': 'Lost Gold Of World War II',
    'louie': 'Louie (2010)',
    'love death and robots': 'Love, Death & Robots',
    'love life': 'Love Life (2020)',
    'love victor': 'Love, Victor',
    'luis miguel': 'Luis Miguel - The Series',
    'luis miguel the series': 'Luis Miguel - The Series',
    'luke bryan my dirt road diary': 'Luke Bryan - My Dirt Road Diary',
    'macgyver (2016)': 'MacGyver (2016)',
    'macgyver': 'MacGyver (2016)',
    'magi': 'Magi - The Labyrinth Of Magic',
    'magi the labyrinth of magic': 'Magi - The Labyrinth Of Magic',
    'the magicians': 'The Magicians (2015)',
    'magnum pi': 'Magnum P.I.',
    'magnum p.i': 'Magnum P.I.',
    'maho tsukai no Yome': 'The Ancient Magus\' Bride',
    'mahoutsukai no Yome': 'The Ancient Magus\' Bride',
    'making history': 'Making History (2017)',
    'man vs history': 'Man Vs. History',
    'manhunt unabomber': 'Manhunt',
    'maniac': 'Maniac (2018)',
    'marco polo': 'Marco Polo (2014)',
    'married. with children': 'Married With Children',
    'married... with children': 'Married With Children',
    'mars': 'Mars (2016)',
    'marvel studios assembled': 'Marvel Studios - Assembled',
    'marvel studios legends': 'Marvel Studios - Legends',
    'marvels 616': 'Marvel\'s 616',
    'marvel\'s 616': 'Marvel\'s 616',
    '616': 'Marvel\'s 616',
    'agent carter': 'Marvel\'s Agent Carter',
    'marvels agent carter': 'Marvel\'s Agent Carter',
    'marvel\'s agent carter': 'Marvel\'s Agent Carter',
    'agents of s.h.i.e.l.d.': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'marvels agents of shield': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'marvel\'s agents of shield': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'marvels agents of s.h.i.e.l.d': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'marvel\'s agents of s.h.i.e.l.d': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'marvels agents of s.h.i.e.l.d.': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'marvel\'s agents of s.h.i.e.l.d.': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'cloak & dagger': 'Marvel\'s Cloak & Dagger',
    'cloak and dagger': 'Marvel\'s Cloak & Dagger',
    'marvels cloak & dagger': 'Marvel\'s Cloak & Dagger',
    'marvel\'s cloak & dagger': 'Marvel\'s Cloak & Dagger',
    'marvels cloak and dagger': 'Marvel\'s Cloak & Dagger',
    'marvel\'s cloak and dagger': 'Marvel\'s Cloak & Dagger',
    'daredevil': 'Marvel\'s Daredevil',
    'marvels daredevil': 'Marvel\'s Daredevil',
    'marvel\'s daredevil': 'Marvel\'s Daredevil',
    'falcon & winter soldier': 'Marvel\'s Falcon & Winter Soldier',
    'falcon and winter soldier': 'Marvel\'s Falcon & Winter Soldier',
    'marvels falcon & winter soldier': 'Marvel\'s Falcon & Winter Soldier',
    'marvels falcon and winter soldier': 'Marvel\'s Falcon & Winter Soldier',
    'marvel\'s falcon & winter soldier': 'Marvel\'s Falcon & Winter Soldier',
    'marvel\'s falcon and winter soldier': 'Marvel\'s Falcon & Winter Soldier',
    'hawkeye': 'Marvel\'s Hawkeye',
    'marvels hawkeye': 'Marvel\'s Hawkeye',
    'marvel\'s hawkeye': 'Marvel\'s Hawkeye',
    'iron fist': 'Marvel\'s Iron Fist',
    'marvels iron fist': 'Marvel\'s Iron Fist',
    'marvel\'s iron fist': 'Marvel\'s Iron Fist',
    'jessica jones': 'Marvel\'s Jessica Jones',
    'marvels jessica jones': 'Marvel\'s Jessica Jones',
    'marvel\'s jessica jones': 'Marvel\'s Jessica Jones',
    'loki': 'Marvel\'s Loki',
    'marvels loki': 'Marvel\'s Loki',
    'marvel\'s loki': 'Marvel\'s Loki',
    'luke cage': 'Marvel\'s Luke Cage',
    'marvels luke cage': 'Marvel\'s Luke Cage',
    'marvel\'s luke cage': 'Marvel\'s Luke Cage',
    'marvels modok': 'Marvel\'s M.O.D.O.K.',
    'modok': 'Marvel\'s M.O.D.O.K.',
    'moon knight': 'Marvel\'s Moon Knight',
    'marvels moon knight': 'Marvel\'s Moon Knight',
    'marvel\'s moon knight': 'Marvel\'s Moon Knight',
    'the defenders': 'Marvel\'s The Defenders',
    'marvels the defenders': 'Marvel\'s The Defenders',
    'marvel\'s the defenders': 'Marvel\'s The Defenders',
    'inhumans': 'Marvel\'s Inhumans',
    'marvels inhumans': 'Marvel\'s Inhumans',
    'marvel\'s inhumans': 'Marvel\'s Inhumans',
    'the punisher': 'Marvel\'s The Punisher',
    'marvels the punisher': 'Marvel\'s The Punisher',
    'marvel\'s the punisher': 'Marvel\'s The Punisher',
    'runaways': 'Marvel\'s Runaways',
    'marvels runaways': 'Marvel\'s Runaways',
    'marvel\'s runaways': 'Marvel\'s Runaways',
    'she hulk': 'Marvel\'s She-Hulk',
    'marvels she hulk': 'Marvel\'s She-Hulk',
    'marvel\'s she hulk': 'Marvel\'s She-Hulk',
    'she-hulk': 'Marvel\'s She-Hulk',
    'marvels she-hulk': 'Marvel\'s She-Hulk',
    'marvel\'s she-hulk': 'Marvel\'s She-Hulk',
    'marvels spidey and his amazing friends': 'Marvel\'s Spidey And His Amazing Friends',
    'spidey and his amazing friends': 'Marvel\'s Spidey And His Amazing Friends',
    'marvels what if': 'What If...',
    'marvel\'s what if': 'What If...',
    'what if': 'What If...',
    'masters of the universe revelation': 'Masters Of The Universe - Revelation',
    'mayans': 'Mayans M.C.',
    'mayans mc': 'Mayans M.C.',
    'mayans m.c': 'Mayans M.C.',
    'mayans m.c.': 'Mayans M.C.',
    'mccartney 3, 2, 1': 'McCartney 3, 2, 1',
    'mccartney 3.2.1': 'McCartney 3, 2, 1',
    'mccartney 3 2 1': 'McCartney 3, 2, 1',
    'mcdonald & dodds': 'McDonald & Dodds',
    'mcmafia': 'McMafia',
    'mcmillion': 'McMillion$',
    'mcmillions': 'McMillion$',
    'medici': 'Medici - Masters Of Florence',
    'medici masters of florence': 'Medici - Masters Of Florence',
    'meerkat manor rise of the dynasty': 'Meerkat Manor - Rise Of The Dynasty',
    'mehubarim': 'Mehubarim +',
    'melissa and joey': 'Melissa & Joey',
    'men in kilts': 'Men In Kilts - A Roadtrip With Sam And Graham',
    'men in kilts a roadtrip with sam and graham': 'Men In Kilts - A Roadtrip With Sam And Graham',
    'menayek': 'Manayek',
    'messiah': 'Messiah (2020)',
    'metumtemet': 'Dumb',
    'mayonaka no occult koumuin': 'Midnight Occult Civil Servants',
    'midnight diner': 'Midnight Diner - Tokyo Stories',
    'midnight diner tokyo stories': 'Midnight Diner - Tokyo Stories',
    'midnight texas': 'Midnight, Texas',
    'mike tyson': 'Mike Tyson - The Knockout',
    'mike tyson the knockout': 'Mike Tyson - The Knockout',
    'mixedish': 'Mixed-Ish',
    'mixed-ish': 'Mixed-Ish',
    'mob psycho': 'Mob Psycho 100',
    'money explained': 'Money, Explained',
    'monty pythons flying circus': 'Monty Python\'s Flying Circus',
    'the moodys': 'The Moodys (US)',
    'mortal kombat conquest': 'Mortal Kombat - Conquest',
    'mortal kombat defenders of the realm': 'Mortal Kombat - Defenders Of The Realm',
    'mortal kombat legacy': 'Mortal Kombat - Legacy',
    'motek bull baemzta': 'Motek, Bull Ba\'Hemtza',
    'motek bull baemtza': 'Motek, Bull Ba\'Hemtza',
    'motek, bull baemtza': 'Motek, Bull Ba\'Hemtza',
    'motherfatherson': 'MotherFatherSon',
    'mother father son': 'MotherFatherSon',
    'motherland fort salem': 'Motherland - Fort Salem',
    'mr corman': 'Mr. Corman',
    'mr mayor': 'Mr. Mayor',
    'mr mercedes': 'Mr. Mercedes',
    'mr pickles': 'Mr. Pickles',
    'mr robot': 'Mr. Robot',
    'mr sunshine': 'Mr. Sunshine (2018)',
    'mr. sunshine': 'Mr. Sunshine (2018)',
    'mrs america': 'Mrs. America',
    'mrs. america': 'Mrs. America',
    'ms fishers modern murder mysteries': 'Ms. Fisher\'s Modern Murder Mysteries',
    'ms. fishers modern murder mysteries': 'Ms. Fisher\'s Modern Murder Mysteries',
    'ms fisher\'s modern murder mysteries': 'Ms. Fisher\'s Modern Murder Mysteries',
    'ms marvel': 'Ms. Marvel',
    'ms. marvel': 'Ms. Marvel',
    'murder she wrote': 'Murder, She Wrote',
    'myth & mogul john delorean': 'Myth & Mogul - John DeLorean',
    'myth and mogul john delorean': 'Myth & Mogul - John DeLorean',
    'mythbusters': 'MythBusters',
    'mythic quest': 'Mythic Quest - Raven\'s Banquet',
    'mythic quest ravens banquet': 'Mythic Quest - Raven\'s Banquet',
    'mythic quest raven\'s banquet': 'Mythic Quest - Raven\'s Banquet',
    'nancy drew': 'Nancy Drew (2019)',
    'narcos mexico': 'Narcos - Mexico',
    'nashville': 'Nashville (2012)',
    'ncis': 'NCIS',
    'ncis hawaii': 'NCIS - Hawaii',
    'ncis - hawaii': 'NCIS - Hawaii',
    'ncis los angeles': 'NCIS - Los Angeles',
    'ncis - los angeles': 'NCIS - Los Angeles',
    'ncis new orleans': 'NCIS - New Orleans',
    'ncis - new orleans': 'NCIS - New Orleans',
    'new amsterdam': 'New Amsterdam (2018)',
    'newsroom': 'The Newsroom (2012)',
    'next': 'NeXt (2020)',
    'the newsroom': 'The Newsroom (2012)',
    'night stalker the hunt for a serial killer': 'Night Stalker - The Hunt For A Serial Killer',
    'niptuck': 'NipTuck',
    'nip tuck': 'NipTuck',
    'nos4a2': 'NOS4A2',
    'nurses': 'Nurses (2020)',
    'the oa': 'The OA',
    'obama in pursuit of a more perfect union': 'Obama - In Pursuit Of A More Perfect Union',
    'the office': 'The Office (US)',
    'o j simpson made in america': 'O.J. - Made In America',
    'o.j. simpson made in america': 'O.J. - Made In America',
    'oj simpson made in america': 'O.J. - Made In America',
    'o j made in america': 'O.J. - Made In America',
    'o.j. made in america': 'O.J. - Made In America',
    'oj made in america': 'O.J. - Made In America',
    'ok ko': 'OK K.O.! Let\'s Be Heroes',
    'ok k o': 'OK K.O.! Let\'s Be Heroes',
    'ok k.o': 'OK K.O.! Let\'s Be Heroes',
    'ok k.o.': 'OK K.O.! Let\'s Be Heroes',
    'ok ko lets be heroes': 'OK K.O.! Let\'s Be Heroes',
    'ok k o lets be heroes': 'OK K.O.! Let\'s Be Heroes',
    'ok k.o lets be heroes': 'OK K.O.! Let\'s Be Heroes',
    'ok k.o. lets be heroes': 'OK K.O.! Let\'s Be Heroes',
    'ok ko - lets be heroes': 'OK K.O.! Let\'s Be Heroes',
    'ok k o - lets be heroes': 'OK K.O.! Let\'s Be Heroes',
    'ok k.o - lets be heroes': 'OK K.O.! Let\'s Be Heroes',
    'ok k.o. - lets be heroes': 'OK K.O.! Let\'s Be Heroes',
    'once upon a time': 'Once Upon A Time (2011)',
    'one day at a time': 'One Day At A Time (2017)',
    'one punch man': 'One-Punch Man',
    'onegai teacher': 'Please Teacher!',
    'onegai teacher!': 'Please Teacher!',
    'please teacher': 'Please Teacher!',
    'our planet': 'Our Planet (2019)',
    'ozzy and jacks world detour': 'Ozzy And Jack\'s World Detour',
    'pacific rim the black': 'Pacific Rim - The Black',
    'pamta': 'Red Lines',
    'panic': 'Panic (2021)',
    'parades end': 'Parade\'s End',
    'paradise lost': 'Paradise Lost (2020)',
    'paradise pd': 'Paradise PD',
    'parasyte': 'Parasyte - The Maxim',
    'parasyte the maxim': 'Parasyte - The Maxim',
    'party of five': 'Party Of Five (2020)',
    'patriot': 'Patriot (2017)',
    'pen15': 'PEN15',
    'penguins spy in the huddle': 'Penguins - Spy In The Huddle',
    'penny dreadful city of angels': 'Penny Dreadful - City Of Angels',
    'perry mason': 'Perry Mason (2020)',
    'phantom': 'Phantom - Requiem For The Phantom',
    'phantom requiem for the phantom': 'Phantom - Requiem For The Phantom',
    'philip k dicks electric dreams': 'Philip K. Dick\'s Electric Dreams',
    'philip k dick\'s electric dreams': 'Philip K. Dick\'s Electric Dreams',
    'philip k. dicks electric dreams': 'Philip K. Dick\'s Electric Dreams',
    'ping pong': 'Ping Pong - The Animation',
    'ping pong the animation': 'Ping Pong - The Animation',
    'pinocchio': 'Pinocchio - The Series',
    'planet earth ii': 'Planet Earth II',
    'poldark': 'Poldark (2015)',
    'polyshuk': 'Polishuk',
    'power book ii ghost': 'Power Book II - Ghost',
    'power book ii - ghost': 'Power Book II - Ghost',
    'power book iii raising kanan': 'Power Book III - Raising Kanan',
    'power book iii - raising kanan': 'Power Book III - Raising Kanan',
    'pretty little liars the perfectionists': 'Pretty Little Liars - The Perfectionists',
    'pride and prejudice': 'Pride And Prejudice (1995)',
    'professor t': 'Professor T (2021)',
    'the protector': 'The Protector (2018)',
    'psycho-pass': 'Psycho-Pass',
    'punky brewster': 'Punky Brewster (2021)',
    'qi': 'QI',
    'raised by wolves': 'Raised By Wolves (2020)',
    'rebel': 'Rebel (2021)',
    'reboot the guardian code': 'ReBoot - The Guardian Code',
    'reno 911': 'Reno 911!',
    'resident evil infinite darkness': 'RESIDENT EVIL - Infinite Darkness',
    'rise': 'Rise (2018)',
    'rizzoli and isles': 'Rizzoli & Isles',
    'r o d': 'R.O.D - Read Or Die',
    'r.o.d': 'R.O.D - Read Or Die',
    'read or die': 'R.O.D - Read Or Die',
    'reign': 'Reign (2013)',
    'roadkill': 'Roadkill (2020)',
    'r.o.d read or die': 'R.O.D - Read Or Die',
    'roots': 'Roots (2016)',
    'roswell new': 'Roswell, New Mexico',
    'roswell new mexico': 'Roswell, New Mexico',
    'rugrats': 'Rugrats (2021)',
    'run': 'Run (2020)',
    'satsuriku no tenshi': 'Angels Of Death',
    'saved by the bell': 'Saved By The Bell (2020)',
    'saved by the bell the new class': 'Saved By The Bell - The New Class',
    'saved by the bell the college years': 'Saved By The Bell - The College Years',
    'scandal': 'Scandal (2012)',
    'schitts creek': 'Schitt\'s Creek',
    'schmigadoon': 'Schmigadoon!',
    'search party': 'Search Party (2016)',
    'second chance': 'Second Chance (2016)',
    'selena': 'Selena - The Series',
    'selena the series': 'Selena - The Series',
    'self made': 'Self Made - Inspired By The Life Of Madam C.J. Walker',
    'self made inspired by the life of madam cj walker': 'Self Made - Inspired By The Life Of Madam C.J. Walker',
    'self made inspired by the life of madam c.j walker': 'Self Made - Inspired By The Life Of Madam C.J. Walker',
    'self made inspired by the life of madam c.j. walker': 'Self Made - Inspired By The Life Of Madam C.J. Walker',
    'self made inspired by the life of madam c j walker': 'Self Made - Inspired By The Life Of Madam C.J. Walker',
    'self made - inspired by the life of madam cj walker': 'Self Made - Inspired By The Life Of Madam C.J. Walker',
    'self made - inspired by the life of madam c.j walker': 'Self Made - Inspired By The Life Of Madam C.J. Walker',
    'self made - inspired by the life of madam c.j. walker': 'Self Made - Inspired By The Life Of Madam C.J. Walker',
    'self made - inspired by the life of madam c j walker': 'Self Made - Inspired By The Life Of Madam C.J. Walker',
    'sex life': 'Sex-Life',
    'shababnikim': 'The New Black',
    'shadowhunters the mortal instruments': 'Shadowhunters',
    'shameless': 'Shameless (US)',
    'shameless us': 'Shameless (US)',
    'shangrila': 'Shangri-La (2019)',
    'shangri-la': 'Shangri-La (2019)',
    'shangri la': 'Shangri-La (2019)',
    'shat neila': 'Valley Of Tears',
    'sh\'at neila': 'Valley Of Tears',
    'shermans showcase': 'Sherman\'s Showcase',
    'shigatsu wa kimi no uso': 'Your Lie In April',
    'siren': 'Siren (2018)',
    'six': 'SIX',
    'smurfs': 'The Smurfs',
    'snowfall': 'Snowfall (2017)',
    'somali to mori no kamisama': 'Somali And The Forest Spirit',
    'somos': 'Somos.',
    'sora yori mo tooi basho': 'A Place Further Than The Universe',
    'sophie a murder in west cork': 'Sophie - A Murder In West Cork',
    'soul eater not': 'Soul Eater Not!',
    'spiderman': 'Spider-Man (1994)',
    'spider man': 'Spider-Man (1994)',
    'spider-man': 'Spider-Man (1994)',
    'splitting up together': 'Splitting Up Together (US)',
    'spongebob': 'SpongeBob SquarePants',
    'spongebob squarepants': 'SpongeBob SquarePants',
    'ss': 'SS-GB',
    'ss gb': 'SS-GB',
    'ss-gb': 'SS-GB',
    'star vs the forces of evil': 'Star Vs. The Forces Of Evil',
    'stargate atlantis': 'Stargate Atlantis',
    'stargate origins': 'Stargate - Origins',
    'stargate': 'Stargate SG-1',
    'stargate sg-1': 'Stargate SG-1',
    'stargate sg 1': 'Stargate SG-1',
    'star trek tos': 'Star Trek',
    'star trek (tos)': 'Star Trek',
    'star trek ds9': 'Stark Trek - Deep Space Nine',
    'star trek deep space 9': 'Stark Trek - Deep Space Nine',
    'star trek deep space nine': 'Stark Trek - Deep Space Nine',
    'star trek discovery': 'Star Trek - Discovery',
    'star trek enterprise': 'Star Trek - Enterprise',
    'star trek lower decks': 'Star Trek - Lower Decks',
    'star trek picard': 'Star Trek - Picard',
    'star trek short treks': 'Star Trek - Short Treks',
    'star trek tng': 'Star Trek - The Next Generation',
    'star trek (tng)': 'Star Trek - The Next Generation',
    'star trek the next generation': 'Star Trek - The Next Generation',
    'star trek voyager': 'Star Trek - Voyager',
    'star wars the clone wars': 'Star Wars - The Clone Wars',
    'star wars': 'Star Wars - Rebels',
    'star wars rebels': 'Star Wars - Rebels',
    'star wars resistance': 'Star Wars - Resistance',
    'star wars the bad batch': 'The Bad Batch',
    'startup': 'StartUp (2016)',
    'steinsgate': 'Steins;Gate',
    'steins gate': 'Steins;Gate',
    'steinsgate 0': 'Steins;Gate 0',
    'steins gate 0': 'Steins;Gate 0',
    'strangers': 'Strangers (2018)',
    'sunderland til i die': 'Sunderland \'Til I Die',
    'superman and lois': 'Superman & Lois',
    'surrealestate': 'SurrealEstate',
    'surviving r kelly': 'Surviving R. Kelly',
    'surviving r. kelly': 'Surviving R. Kelly',
    'surviving r.kelly': 'Surviving R. Kelly',
    'swamp thing': 'Swamp Thing (2019)',
    's w a t': 'S.W.A.T. (2017)',
    's.w a t': 'S.W.A.T. (2017)',
    's.w.a t': 'S.W.A.T. (2017)',
    's.w.a.t': 'S.W.A.T. (2017)',
    's.w.a.t.': 'S.W.A.T. (2017)',
    's w a.t.': 'S.W.A.T. (2017)',
    's w.a.t.': 'S.W.A.T. (2017)',
    'sword art online alternative gun gale online': 'Sword Art Online Alternative - Gun Gale Online',
    'taagad': 'Charlie Golf One',
    'taboo': 'Taboo (2017)',
    'tacoma fd': 'Tacoma FD',
    'tacoma f d': 'Tacoma FD',
    'taken': 'Taken (2017)',
    'tate no yuusha no nariagari': 'The Rising Of The Shield Hero',
    'ted bundy falling for a killer': 'Ted Bundy - Falling For A Killer',
    'tell me a story': 'Tell Me A Story (US)',
    'terminator': 'Terminator - The Sarah Connor Chronicles',
    'terminator the sarah connor chronicles': 'Terminator - The Sarah Connor Chronicles',
    'that 70s show': 'That 70\'s Show',
    'that 70\'s show': 'That 70\'s Show',
    'the adventures of jimmy neutron boy genius': 'The Adventures Of Jimmy Neutron - Boy Genius',
    'the bay': 'The Bay (2019)',
    'the code': 'The Code (2019)',
    'the continental': 'The Continental (2021)',
    'the crew': 'The Crew (2021)',
    'the day of the triffids': 'The Day Of The Triffids (2009)',
    'the dictators playbook': 'The Dictator\'s Playbook',
    'the dictator\'s playbook': 'The Dictator\'s Playbook',
    'the end': 'The End (AU)',
    'the equalizer': 'The Equalizer (2021)',
    'the family': 'The Family (2019)',
    'the family man': 'The Family Man (2019)',
    'the forgotten army': 'The Forgotten Army - Azaadi Ke Liye',
    'the forgotten army azaadi ke liye': 'The Forgotten Army - Azaadi Ke Liye',
    'the hardy boys': 'The Hardy Boys (2020)',
    'the i land': 'The I-Land',
    'the i-land': 'The I-Land',
    'the kingdom': 'The Kingdom (2021)',
    'the kings': 'The Kings (2021)',
    'the last og': 'The Last O.G.',
    'the last o.g': 'The Last O.G.',
    'the last o.g.': 'The Last O.G.',
    'the librarians': 'The Librarians (2014)',
    'marvelous mrs maisel': 'The Marvelous Mrs. Maisel',
    'marvelous mrs. maisel': 'The Marvelous Mrs. Maisel',
    'the marvelous mrs maisel': 'The Marvelous Mrs. Maisel',
    'the me you cant see': 'The Me You Can\'t See',
    'the mighty ducks game changers': 'The Mighty Ducks - Game Changers',
    'the mind explained': 'The Mind, Explained',
    'the oc': 'The O.C.',
    'the o.c': 'The O.C.',
    'the o.c.': 'The O.C.',
    'the o c': 'The O.C.',
    'the other one': 'The Other One (2020)',
    'the outsider': 'The Outsider (2020)',
    'the planets': 'The Planets (2019)',
    'the planets uk': 'The Planets (2019)',
    'the politician': 'The Politician (2019)',
    'the queens gambit': 'The Queen\'s Gambit',
    'the queen\'s gambit': 'The Queen\'s Gambit',
    'the ranch': 'The Ranch (2016)',
    'the secret life of 4 year olds': 'The Secret Life Of 4 Year Olds (IL)',
    'the secret life of 4 year olds il': 'The Secret Life Of 4 Year Olds (IL)',
    'the secret life of the 4 year olds': 'The Secret Life Of 4 Year Olds (IL)',
    'the secret life of the 4 year olds il': 'The Secret Life Of 4 Year Olds (IL)',
    'the snitch cartel origins': 'The Snitch Cartel - Origins',
    'the sons of sam': 'The Sons Of Sam - A Descent Into Darkness',
    'the sons of sam a descent into darkness': 'The Sons Of Sam - A Descent Into Darkness',
    'the stand': 'The Stand (2020)',
    'the stranger': 'The Stranger (2020)',
    'the surgeons cut': 'The Surgeon\'s Cut',
    'the tick': 'The Tick (2016)',
    'the tomorrow people': 'The Tomorrow People (US)',
    'the victims game': 'The Victim\'s Game',
    'the victim\'s game': 'The Victim\'s Game',
    'the walking dead origins': 'The Walking Dead - Origins',
    'the walking dead world beyond': 'The Walking Dead - World Beyond',
    'the watch': 'The Watch (2021)',
    'them': 'THEM',
    'this is': 'This Is Us',
    'tiger king': 'Tiger King - Murder, Mayhem And Madness',
    'tiger king murder mayhem and madness': 'Tiger King - Murder, Mayhem And Madness',
    'tiger king - murder mayhem and madness': 'Tiger King - Murder, Mayhem And Madness',
    'tiger king murder, mayhem and madness': 'Tiger King - Murder, Mayhem And Madness',
    'tihon hashir shelanu': 'Our Song High School',
    'time': 'Time (2021)',
    'timeless': 'Timeless (2016)',
    'titans': 'Titans (2018)',
    'tom clancys jack ryan': 'Tom Clancy\'s Jack Ryan',
    'top secret ufo projects declassified': 'Top Secret UFO Projects - Declassified',
    'touch': 'Touch (2012)',
    'transformers war for cybertron': 'Transformers - War For Cybertron Trilogy',
    'transformers war for cybertron trilogy': 'Transformers - War For Cybertron Trilogy',
    'travelers': 'Travelers (2016)',
    'trollhunters': 'Trollhunters - Tales Of Arcadia',
    'trollhunters tales of arcadia': 'Trollhunters - Tales Of Arcadia',
    'troy fall of a city': 'Troy - Fall Of A City',
    'trump an american dream': 'Trump - An American Dream',
    'trust': 'Trust (2018)',
    'trust me': 'Trust Me (2017)',
    'tuca and bertie': 'Tuca & Bertie',
    'turn': 'TURN - Washington\'s Spies',
    'turn washingtons spies': 'TURN - Washington\'s Spies',
    'turn - washingtons spies': 'TURN - Washington\'s Spies',
    'turn washington\'s spies': 'TURN - Washington\'s Spies',
    'turn - washington\'s spies': 'TURN - Washington\'s Spies',
    'turner and hooch': 'Turner & Hooch',
    'the twilight zone': 'The Twilight Zone (2019)',
    'tzel shel emet': 'Shadow Of Truth',
    'ufo': 'UFO (2021)',
    'undercover billionaire comeback city': 'Undercover Billionaire - Comeback City',
    'undertaker the last ride': 'Undertaker - The Last Ride',
    'wwe undertaker the last ride': 'Undertaker - The Last Ride',
    'unreal': 'UnREAL',
    'unsolved': 'Unsolved - The Murders Of Tupac And The Notorious B.I.G.',
    'unsolved the murders of tupac and the notorious big': 'Unsolved - The Murders Of Tupac And The Notorious B.I.G.',
    'unsolved the murders of tupac and the notorious b.i.g.':
        'Unsolved - The Murders Of Tupac And The Notorious B.I.G.',
    'unsolved - the murders of tupac and the notorious big': 'Unsolved - The Murders Of Tupac And The Notorious B.I.G.',
    'unsolved - the murders of tupac and the notorious b.i.g':
        'Unsolved - The Murders Of Tupac And The Notorious B.I.G.',
    'utopia': 'Utopia (2020)',
    'unwell': '(Un)Well',
    'unxplained': 'The UnXplained',
    'the unxplained': 'The UnXplained',
    'v': 'V (2009)',
    'van der valk': 'Van Der Valk (2020)',
    'the venture bros': 'The Venture Bros.',
    'vice': 'VICE',
    'the vietnam war': 'The Vietnam War (2017)',
    'vikings valhalla': 'Vikings - Valhalla',
    'vis a vis': 'Locked Up',
    'walker texas ranger': 'Walker, Texas Ranger',
    'walt disney animation studios short circuit experimental films':
        'Walt Disney Animation Studios - Short Circuit Experimental Films',
    'wandavision': 'WandaVision',
    'war of the worlds': 'War Of The Worlds (2019)',
    'warrior': 'Warrior (2019)',
    'watership down': 'Watership Down (2018)',
    'we are the brooklyn saints': 'We Are - The Brooklyn Saints',
    'welcome to': 'Welcome To Sweden (2014)',
    'welcome to sweden': 'Welcome To Sweden (2014)',
    'whats my name': 'What\'s My Name - Muhammad Ali',
    'whats my name muhammad ali': 'What\'s My Name - Muhammad Ali',
    'when they see': 'When They See Us',
    'whitest kids u know': 'The Whitest Kids U\'Know',
    'the whitest kids u know': 'The Whitest Kids U\'Know',
    'wilfred': 'Wilfred (US)',
    'will and grace': 'Will & Grace',
    'wizards': 'Wizards - Tales Of Arcadia',
    'wizards tales of arcadia': 'Wizards - Tales Of Arcadia',
    'workin moms': 'Workin\' Moms',
    'world war ii in': 'World War II In HD Colour',
    'world war ii in hd colour': 'World War II In HD Colour',
    'the worlds most extraordinary homes': 'The World\'s Most Extraordinary Homes',
    'wormwood': 'Wormwood (2017)',
    'wrecked': 'Wrecked (2016)',
    'wu assassins': 'WU Assassins',
    'wu tang': 'Wu-Tang - An American Saga',
    'wu-tang': 'Wu-Tang - An American Saga',
    'wu tang an american saga': 'Wu-Tang - An American Saga',
    'wu-tang an american saga': 'Wu-Tang - An American Saga',
    'the x files': 'The X-Files',
    'x men': 'X-Men - The Animated Series',
    'x men the animated series': 'X-Men - The Animated Series',
    'xena': 'Xena - Warrior Princess',
    'xena warrior princess': 'Xena - Warrior Princess',
    'yakusoku no neverland': 'The Promised Neverland',
    'yellowstone': 'Yellowstone (2018)',
    'you': 'YOU',
    'your honor': 'Your Honor (US)',
    'youre the worst': 'You\'re The Worst',
    'zaguri imperya': 'Zaguri Empire',
    'zero zero zero': 'ZeroZeroZero',
    'zerozerozero': 'ZeroZeroZero',
    'zetsuen no tempest': 'Blast Of Tempest',
    'zoeys extraordinary playlist': 'Zoey\'s Extraordinary Playlist',
    'zot ve zoti': 'Zot VeZoti',
    'zot vezoti': 'Zot VeZoti'
}
